In [35]:
import requests
import json
from apikeys import av_key
import pandas as pd
import os
import csv
import sys

In [3]:
base_url = 'https://www.alphavantage.co/query?function='


sector_url = base_url +'SECTOR&apikey='+ av_key


sector_response = requests.get(sector_url)

response_json = sector_response.json()
print(json.dumps(response_json, indent=4, sort_keys=True))

{
    "Meta Data": {
        "Information": "US Sector Performance (realtime & historical)",
        "Last Refreshed": "04:20 PM ET 06/26/2018"
    },
    "Rank A: Real-Time Performance": {
        "Consumer Discretionary": "0.68%",
        "Consumer Staples": "-0.45%",
        "Energy": "1.40%",
        "Financials": "-0.37%",
        "Health Care": "-0.28%",
        "Industrials": "0.33%",
        "Information Technology": "0.48%",
        "Materials": "0.36%",
        "Real Estate": "0.50%",
        "Telecommunication Services": "-0.42%",
        "Utilities": "-0.01%"
    },
    "Rank B: 1 Day Performance": {
        "Consumer Discretionary": "-2.18%",
        "Consumer Staples": "0.44%",
        "Energy": "-2.20%",
        "Financials": "-1.03%",
        "Health Care": "-0.90%",
        "Industrials": "-1.24%",
        "Information Technology": "-2.28%",
        "Materials": "-1.46%",
        "Real Estate": "-0.18%",
        "Telecommunication Services": "-0.08%",
        "Utilities": "1.65%"
    },
    "Rank C: 5 Day Performance": {
        "Consumer Discretionary": "-2.68%",
        "Consumer Staples": "2.00%",
        "Energy": "-1.82%",
        "Financials": "-2.37%",
        "Health Care": "-0.57%",
        "Industrials": "-4.23%",
        "Information Technology": "-3.81%",
        "Materials": "-3.27%",
        "Real Estate": "2.43%",
        "Telecommunication Services": "1.41%",
        "Utilities": "3.83%"
    },
    "Rank D: 1 Month Performance": {
        "Consumer Discretionary": "2.92%",
        "Consumer Staples": "4.49%",
        "Energy": "-3.35%",
        "Financials": "-3.88%",
        "Health Care": "1.49%",
        "Industrials": "-5.30%",
        "Information Technology": "-0.40%",
        "Materials": "-2.61%",
        "Real Estate": "4.38%",
        "Telecommunication Services": "-0.73%",
        "Utilities": "3.23%"
    },
    "Rank E: 3 Month Performance": {
        "Consumer Discretionary": "8.70%",
        "Consumer Staples": "1.79%",
        "Energy": "10.19%",
        "Financials": "-0.10%",
        "Health Care": "5.61%",
        "Industrials": "-1.60%",
        "Information Technology": "8.48%",
        "Materials": "2.91%",
        "Real Estate": "7.15%",
        "Telecommunication Services": "-0.54%",
        "Utilities": "5.22%"
    },
    "Rank F: Year-to-Date (YTD) Performance": {
        "Consumer Discretionary": "10.47%",
        "Consumer Staples": "-9.30%",
        "Energy": "1.91%",
        "Financials": "-4.04%",
        "Health Care": "1.90%",
        "Industrials": "-5.50%",
        "Information Technology": "10.07%",
        "Materials": "-4.67%",
        "Real Estate": "-2.17%",
        "Telecommunication Services": "-11.92%",
        "Utilities": "-2.10%"
    },
    "Rank G: 1 Year Performance": {
        "Consumer Discretionary": "21.62%",
        "Consumer Staples": "-7.01%",
        "Energy": "14.48%",
        "Financials": "12.23%",
        "Health Care": "4.63%",
        "Industrials": "3.38%",
        "Information Technology": "25.76%",
        "Materials": "6.84%",
        "Real Estate": "-0.81%",
        "Telecommunication Services": "-6.06%",
        "Utilities": "-3.10%"
    },
    "Rank H: 3 Year Performance": {
        "Consumer Discretionary": "40.78%",
        "Consumer Staples": "7.05%",
        "Energy": "-3.23%",
        "Financials": "32.21%",
        "Health Care": "11.32%",
        "Industrials": "26.17%",
        "Information Technology": "70.24%",
        "Materials": "15.88%",
        "Telecommunication Services": "-6.10%",
        "Utilities": "23.15%"
    },
    "Rank I: 5 Year Performance": {
        "Consumer Discretionary": "100.68%",
        "Consumer Staples": "31.20%",
        "Energy": "-4.33%",
        "Financials": "75.75%",
        "Health Care": "79.26%",
        "Industrials": "66.88%",
        "Information Technology": "151.92%",
        "Materials": "49.86%",
        "Telecommunication Services": "-4.66%",
        "Utilities": "40.88%"
    },
    "Rank J: 10 Year Performance": {
        "Consumer Discretionary": "273.77%",
        "Consumer Staples": "90.39%",
        "Energy": "-15.79%",
        "Financials": "52.17%",
        "Health Care": "175.57%",
        "Industrials": "91.03%",
        "Information Technology": "229.85%",
        "Materials": "34.85%",
        "Telecommunication Services": "7.31%",
        "Utilities": "25.81%"
    }
}

In [78]:
symbol = '^GSPC' # ^GSPC is SP 500


time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol+'&outputsize=full&apikey='+ av_key

daily_response = requests.get(time_series_url)
                          
response_json2 = daily_response.json()   

opening = []
closing = []
date = []


for key in response_json2["Time Series (Daily)"]:
    
    opening.append(response_json2["Time Series (Daily)"][key]["1. open"])
    closing.append(response_json2["Time Series (Daily)"][key]["4. close"])
    date.append(key)

sp_df = pd.DataFrame({
    'Date': date,
    'S&P500 Open': opening,
    'S&P500 Close': closing
})


sp_df = sp_df[["Date", "S&P500 Open","S&P500 Close"]]
sp_df = sp_df.sort_values('Date', ascending = True)  

sp_df.head()

            Date S&P500 Open S&P500 Close
4649  2000-01-03   1469.2500    1455.2200
4648  2000-01-04   1455.2200    1399.4200
4647  2000-01-05   1399.4200    1402.1100
4646  2000-01-06   1402.1100    1403.4500
4645  2000-01-07   1403.4500    1441.4700

In [81]:
# Loop to calculate

same_day =[]
one_day = []
two_day =[]

for row in range(len(sp_df)):
   same_day_open= float(sp_df["S&P500 Open"][row])
   same_day_close= float(sp_df["S&P500 Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   same_day.append(same_day_change)
   
   if row + 1 < len(sp_df):
       prev_day_close= float(sp_df["S&P500 Close"][row])
       next_day_close = float(sp_df["S&P500 Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       one_day.append(one_day_change)

   if row + 2 < len(sp_df):
       prev_day_close= float(sp_df["S&P500 Close"][row])
       
       two_day_close = float(sp_df["S&P500 Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       two_day.append(two_day_change)
       
   else:
       two_day_change = 0
       two_day.append(two_day_change)

   
   
print (same_day[0])
print (same_day[252])

print (one_day[0])
print (one_day[251])

print (two_day[0])
print (two_day[252])

0.03
-0.17
-0.22
0.81
1.17
-0.19

In [82]:
sp_df["Same Day Change"] = same_day
sp_df["One Day Change"] = one_day
sp_df["Two Day Change"] = two_day


sp_df.head()

,Date,S&P500 Open,S&P500 Close,Same Day Change,One Day Change,Two Day Change
4649,2000-01-03,1469.2500,1455.2200,0.03,-0.22,1.17
4648,2000-01-04,1455.2200,1399.4200,-0.94,1.39,1.20
4647,2000-01-05,1399.4200,1402.1100,-0.21,-0.19,0.45
4646,2000-01-06,1402.1100,1403.4500,-0.70,0.64,0.47
4645,2000-01-07,1403.4500,1441.4700,-0.09,-0.17,0.23

2769.28

'2018-06-25'