In [1]:
#Dependencies
import pandas as pd
import tweepy
from datetime import datetime as dt
from datetime import date
from datetime import timedelta
from pprint import pprint
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
from time import strftime
import math


from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

import matplotlib.dates as mdates
import matplotlib.cbook as cbook
from apikeys import consumer_key, consumer_secret, access_token, access_token_secret




import requests
import json
from apikeys import av_key
import pandas as pd
import os
import csv
import sys

from functools import reduce
from scipy import stats

In [2]:
# Setup Tweepy API Authentication
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())

In [3]:
# Target User
target_user = "@realDonaldTrump"


# Variable to hold Tweet Texts, created date, number of retweets, number of likes
tweet_texts = []
created_date =[]
retweets=[]
likes=[]


# Create a loop to iteratively run API requests to bypass weekly tweeter API limit
for x in range(1,160):

    # Get all tweets from Trump home feed (for specified number of pages)
    public_tweets = api.user_timeline(target_user, page=x)

    # Loop through all tweets
    for tweet in public_tweets:
        #Converting text to lower case
        txt = tweet['text'].lower()
        tweet_texts.append(txt)
        created_date.append(tweet["created_at"])
        retweets.append(tweet["retweet_count"])
        likes.append(tweet["favorite_count"])
        
#Created new dictionary to hold above variables
trump_tweets = {
                "Tweet" : tweet_texts,
                "Date" : created_date,
                "Retweets" : retweets,
                "Likes" : likes,
                }

#Converted dictionary to dataframe 
trump_tweets = pd.DataFrame(trump_tweets)
trump_tweets.head(5)

trump_tweets.to_csv("Resource_CSVs/Twitter_RawData.csv", index=False, header=True,encoding='utf-8-sig')
# print(len(trump_tweets))

In [4]:
# Write to CSV -- to insure code runs if there is no internet connectivity and API can't be called
trump_tweets=pd.read_csv('Resource_CSVs/Twitter_RawData.csv')
type(trump_tweets)
trump_tweets

,Tweet,Date,Retweets,Likes
0,"rt @dhsgov: today, dhs, @cbp, and @icegov will...",Mon Jul 02 16:29:17 +0000 2018,6508,0
1,congratulations to andres manuel lopez obrador...,Mon Jul 02 03:01:30 +0000 2018,63356,181547
2,rt @larryelder: beware! #trumpderangementsyndr...,Sun Jul 01 23:24:17 +0000 2018,10646,0
3,"a big week, especially with our numerous victo...",Sun Jul 01 19:39:28 +0000 2018,24099,111996
4,"the liberal left, also known as the democrats,...",Sun Jul 01 12:11:05 +0000 2018,28591,122898
5,i will be interviewed by @mariabartiromo at 10...,Sun Jul 01 12:00:03 +0000 2018,7854,45831
6,"when people come into our country illegally, w...",Sat Jun 30 19:44:09 +0000 2018,36967,144738
7,i will be interviewed by @mariabartiromo on su...,Sat Jun 30 19:31:42 +0000 2018,9563,47143
8,either we need to elect more republicans in no...,Sat Jun 30 19:26:12 +0000 2018,22524,89798
9,i never pushed the republicans in the house to...,Sat Jun 30 19:17:42 +0000 2018,14762,64566
10,a friend of mine and a man who has truly seen ...,Sat Jun 30 19:05:48 +0000 2018,14856,73838
11,i will be making my choice for justice of the ...,Sat Jun 30 12:33:55 +0000 2018,20909,103119
12,just spoke to king salman of saudi arabia and ...,Sat Jun 30 11:37:03 +0000 2018,40726,148609
13,"to the great and brave men and women of ice, d...",Sat Jun 30 11:22:41 +0000 2018,37520,144901
14,the democrats are making a strong push to abol...,Sat Jun 30 11:07:30 +0000 2018,26571,108230
15,rt @danscavino: “@govmikehuckabee: trump could...,Sat Jun 30 10:59:46 +0000 2018,11420,0
16,rt @realdonaldtrump: six months after our tax ...,Sat Jun 30 10:59:04 +0000 2018,19289,0
17,rt @realdonaldtrump: before going any further ...,Sat Jun 30 10:57:05 +0000 2018,12062,0
18,rt @ivankatrump: thank you @secpompeo. \nit wa...,Sat Jun 30 10:49:42 +0000 2018,7332,0
19,rt @ivankatrump: thank you senator alexander f...,Sat Jun 30 10:49:20 +0000 2018,4268,0
20,the new plant being built by foxconn in wiscon...,Fri Jun 29 23:30:02 +0000 2018,15311,75464
21,"rt @foxbusiness: .@ivankatrump: ""i think one o...",Fri Jun 29 23:21:33 +0000 2018,7448,0
22,rt @scavino45: “@icegov new york operation lea...,Fri Jun 29 23:20:18 +0000 2018,11527,0
23,"six months after our tax cuts, more than 6 mil...",Fri Jun 29 18:06:13 +0000 2018,19289,83781
24,"before going any further today, i want to addr...",Fri Jun 29 17:59:22 +0000 2018,12062,58103
25,"prior to departing wisconsin, i was briefed on...",Thu Jun 28 20:49:55 +0000 2018,18389,98508
26,america is open for business! \nhttps://t.co/f...,Thu Jun 28 19:09:42 +0000 2018,12671,55534
27,"today, we broke ground on a plant that will pr...",Thu Jun 28 18:57:22 +0000 2018,22027,96059
28,"i am in milwaukee, wisconsin, for meetings. so...",Thu Jun 28 13:06:01 +0000 2018,16538,89794
29,....persecuted on old and/or totally unrelated...,Thu Jun 28 12:56:17 +0000 2018,17335,73485
...,...,...,...,...
3145,rt @foxandfriends: wall street hits record hig...,Fri Jun 02 10:08:24 +0000 2017,9105,0
3146,make america great again!,Fri Jun 02 01:00:35 +0000 2017,45866,156774
3147,my job as president is to do everything within...,Thu Jun 01 22:50:29 +0000 2017,21372,89235
3148,join me live at the @whitehouse.\n\n➡️https://...,Thu Jun 01 19:03:10 +0000 2017,6778,36830
3149,"the big story is the ""unmasking and surveillan...",Thu Jun 01 11:05:21 +0000 2017,24170,88000
3150,i will be announcing my decision on paris acco...,Thu Jun 01 01:05:17 +0000 2017,16463,75875
3151,crooked hillary clinton now blames everybody b...,Thu Jun 01 00:40:01 +0000 2017,27584,109100
3152,it was an honor to welcome the prime minister ...,Wed May 31 21:52:54 +0000 2017,7070,41645
3153,we traveled the world to strengthen long-stand...,Wed May 31 20:04:45 +0000 2017,12525,57558
3154,i will be announcing my decision on the paris ...,Wed May 31 13:08:41 +0000 2017,13194,69332
3155,"hopefully republican senators, good people all...",Wed May 31 13:05:14 +0000 2017,11703,62861
3156,kathy griffin should be ashamed of herself. my...,Wed May 31 11:14:48 +0000 2017,50114,184795
3157,...case against him &amp; now wants to clear h...,Wed May 31 10:45:27 +0000 2017,12341,56472
3158,"so now it is reported that the democrats, who ...",Wed May 31 10:37:42 +0000 2017,13143,53438
3159,"who can figure out the true meaning of ""covfef...",Wed May 31 10:09:22 +0000 2017,79656,199097
3160,rt @foxandfriends: jared kushner didn't sugges...,Tue May 30 14:01:16 +0000 2017,7165,0
3161,rt @scavino45: president trump pays respects a...,Tue May 30 14:00:50 +0000 2017,5964,0
3162,"the u.s. senate should switch to 51 votes, imm...",Tue May 30 13:59:28 +0000 2017,18760,74035
3163,russian officials must be laughing at the u.s....,Tue May 30 11:04:48 +0000 2017,20516,82007
3164,"we have a massive trade deficit with germany, ...",Tue May 30 10:40:36 +0000 2017,21512,84942
3165,i look forward to paying my respects to our br...,Mon May 29 12:36:37 +0000 2017,14213,88153
3166,today we remember the men and women who made t...,Mon May 29 12:35:34 +0000 2017,34793,145142
3167,north korea has shown great disrespect for the...,Mon May 29 12:18:52 +0000 2017,11853,62376
3168,honoring the men and women who made the ultima...,Mon May 29 12:11:59 +0000 2017,25374,101673
3169,the fake news media works hard at disparaging ...,Mon May 29 00:20:11 +0000 2017,27956,110078
3170,the massive tax cuts/reform that i have submit...,Mon May 29 00:07:01 +0000 2017,14921,71976
3171,i suggest that we add more dollars to healthca...,Sun May 28 23:57:19 +0000 2017,12856,67156
3172,british prime minister may was very angry that...,Sun May 28 14:43:53 +0000 2017,15706,66525
3173,does anyone notice how the montana congression...,Sun May 28 12:45:45 +0000 2017,13939,66931
3174,....it is very possible that those sources don...,Sun May 28 12:45:16 +0000 2017,12439,56786

In [5]:
# Created list of key words
# keywords = ['sad','earnings', 'election', 'futures', 'investor', 'low', 'market', 'nasdaq', 'north korea', 'stock',
# 'market', 'correction', 'trading', 'unemployment','wall street','china','ban',
# 'bull', 'kim', 'price', 'high', 'corporate', 'global warming', 'tariff', 'tax cut', 'jobs', 'economy', 'trade', 'missile', 'nuclear', 'jobs', 'wages',
# 'maga']

In [6]:
keywords=pd.read_csv('Resource_CSVs/keywords.csv')
type(keywords)

pandas.core.frame.DataFrame

In [7]:
#Filtered tweets based on keywords and defined variables to hold
filtered_tweet_texts = []
filtered_created_date =[]
filtered_retweets=[]
filtered_likes=[]
filtered_id=[]
keys=[]
#Variables to hold sentiment analysis
compound_list = []
pos_list = []
neu_list = []
neg_list = []
# i = 0

# Looping through tweets
for tweet in trump_tweets.iterrows():
    for key in keywords['keywords']:
        #Used regular expression to find specific tweets based on keyword
        if re.search(key,tweet[1]['Tweet']):
            #Not all tweets will have keyword, catching tweets that match
            try:
                filtered_tweet_texts.append(tweet[1]["Tweet"])
                filtered_created_date.append(tweet[1]["Date"])
                filtered_retweets.append(tweet[1]["Retweets"])
                filtered_likes.append(tweet[1]["Likes"])
                keys.append(key)
                # Performed sentiment analysis using Vader
                compound = analyzer.polarity_scores(tweet[1]["Tweet"])["compound"]
                pos = analyzer.polarity_scores(tweet[1]["Tweet"])["pos"]
                neu = analyzer.polarity_scores(tweet[1]["Tweet"])["neu"]
                neg = analyzer.polarity_scores(tweet[1]["Tweet"])["neg"]
                compound_list.append(compound)
                pos_list.append(pos)
                neu_list.append(neu)
                neg_list.append(neg)
#                 i += 1   
            except:
                    print('Missing Data')                      
#Create new dictionary for filtered tweets

filtered_trump_tweets = {
                "Tweet" : filtered_tweet_texts,
                "Date" : filtered_created_date,
                "Retweets" : filtered_retweets,
                "Likes" : filtered_likes,
                "Keyword" : keys,
                "Positive" : pos_list,
                "Negative" : neg_list,
                "Neutral" : neu_list,
                "Compound" : compound_list,
                }               

#Convert dictionary to dataframe
filtered_trump_tweets = pd.DataFrame(filtered_trump_tweets)

#Convert date YYYY/MM/DD format
filtered_trump_tweets["Date"] = pd.to_datetime(filtered_trump_tweets["Date"])
filtered_trump_tweets["Date"] = filtered_trump_tweets["Date"].dt.strftime("%Y-%m-%d")

# filtered_trump_tweets
# Write to CSV
outfile = os.path.join("Filtered_tweets.csv")
filtered_trump_tweets.to_csv(outfile, encoding = "utf-8", index=False, header = True)

In [42]:
# Grouping by Tweets and concatenating keywords
grouped_keywords = filtered_trump_tweets.groupby(['Tweet'])['Keyword'].apply(list).reset_index()


#merged grouped data frame with filtered data frame
merged_table = pd.merge(grouped_keywords, filtered_trump_tweets, on="Tweet")
# merged_table=merged_table.drop_duplicates(['Tweet'], keep=False, inplace=False)

#Dropped unwanted column
merged_table = merged_table.drop(['Keyword_y'], axis=1)

#Dropped duplicate tweets
merged_table=merged_table.drop_duplicates(['Tweet'], keep='first', inplace=False).reset_index()

#Display
merged_table

,index,Tweet,Keyword_x,Date,Retweets,Likes,Positive,Negative,Neutral,Compound
0,0,"""after 14 years, u.s. beef hits chinese market...","[market, market, trade]",2017-07-12,16729,66384,0.300,0.000,0.700,0.7184
1,3,"""america's labor market continues to boom"" job...","[market, market, jobs, jobs, labor]",2017-07-25,11787,48982,0.000,0.000,1.000,0.0000
2,8,"""corporations have never made as much money as...","[jobs, jobs]",2017-08-01,16024,75959,0.117,0.000,0.883,0.4199
3,10,"""dow passes 23,000 for the first time, fueled ...",[earnings],2017-10-17,10853,44334,0.216,0.000,0.784,0.5106
4,11,"""iran hides behind its assertion of technical ...",[nuclear],2017-10-18,11226,40706,0.000,0.227,0.773,-0.6124
5,12,"""the real big story that affects everybody in ...",[tax],2018-06-21,11617,47247,0.143,0.081,0.775,0.3818
6,13,....and has been horrible on virginia economy....,[economy],2017-11-07,6740,33606,0.000,0.296,0.704,-0.5848
7,14,....and it will get even better with tax cuts!...,[tax],2017-11-23,9739,49745,0.238,0.164,0.597,0.2481
8,15,....and japan will put up with this much longe...,[china],2017-07-04,28178,109552,0.000,0.120,0.880,-0.5294
9,16,....because he doesn't even live there! he wan...,[tax],2017-06-19,10098,41229,0.000,0.238,0.762,-0.7177
10,17,....for the middle class. the house and senate...,[tax],2017-11-01,11089,54095,0.114,0.081,0.806,0.2263
11,18,....is making. working very hard on tax cuts f...,"[tax, jobs, jobs]",2017-11-07,6691,41531,0.000,0.244,0.756,-0.4914
12,21,....this now allows for the passage of large s...,[tax],2017-10-20,14441,72706,0.000,0.098,0.902,-0.3595
13,22,....we are finishing our study of tariffs on c...,[tariff],2018-06-26,12657,58936,0.083,0.000,0.917,0.2500
14,23,....we are getting other countries to reduce a...,"[tariff, trade]",2018-06-26,14627,66269,0.000,0.000,1.000,0.0000
15,25,....when i had harley-davidson officials over ...,[tariff],2018-06-26,12581,58368,0.000,0.000,1.000,0.0000
16,26,"...2nd amendment, strong military, isis, histo...","[market, stock, market, unemployment]",2017-10-22,16425,76148,0.424,0.171,0.405,0.8439
17,30,...and voted against the massive tax cut bill....,[tax],2018-05-16,9518,44612,0.127,0.349,0.525,-0.7351
18,31,...and west virginia. the fact is the fake new...,"[market, stock, market, jobs, jobs]",2017-08-07,11264,56921,0.218,0.121,0.661,0.3612
19,36,"...based on that, the military has hit isis ""m...",[price],2017-11-03,14363,68132,0.000,0.172,0.828,-0.5848
20,37,...but complain and obstruct. they made only b...,"[stock, trade]",2018-05-25,14456,65564,0.112,0.221,0.667,-0.4753
21,39,...congress must immediately pass border legis...,[nuclear],2018-04-02,23088,88640,0.000,0.115,0.885,-0.2960
22,40,...got along great with kim jong-un who wants ...,[kim],2018-06-12,18274,83302,0.291,0.000,0.709,0.8316
23,41,...haven’t even started yet! the u.s. has very...,[china],2018-05-16,9509,47628,0.000,0.000,1.000,0.0000
24,42,...if congress gives us the massive tax cuts (...,[tax],2017-10-11,10608,52870,0.000,0.095,0.905,-0.2960
25,43,"...lavar, you could have spent the next 5 to 1...",[china],2017-11-22,36529,155064,0.000,0.118,0.882,-0.4215
26,44,"...massive regulation cuts, 36 new legislative...",[tax],2017-06-18,17002,84496,0.165,0.189,0.645,0.2481
27,45,"...owed to wall street and the banks which, sa...",[ban],2017-09-26,7817,38891,0.141,0.101,0.758,0.0258
28,46,...people are now starting to recognize the am...,[build],2017-10-01,15097,77529,0.273,0.000,0.727,0.8360
29,47,...realize the economy is the best it’s ever b...,[economy],2018-06-13,13638,74718,0.167,0.000,0.833,0.6369
...,...,...,...,...,...,...,...,...,...,...
544,830,while i greatly appreciate the efforts of pres...,[china],2017-06-20,17136,78376,0.206,0.000,0.794,0.7171
545,831,why are democrats fighting massive tax cuts fo...,"[tax, jobs, jobs]",2017-11-16,22455,97660,0.000,0.313,0.687,-0.7424
546,834,"why is it that the wall street journal, though...",[tariff],2018-06-02,19102,80273,0.100,0.000,0.900,0.2732
547,835,why is the nfl getting massive tax breaks whil...,[tax],2017-10-10,30881,133364,0.000,0.000,1.000,0.0000
548,836,why isn’t the european union and canada inform...,"[tariff, trade]",2018-06-08,27076,98480,0.000,0.000,1.000,0.0000
549,838,"why should i, as president of the united state...",[trade],2018-06-11,33564,142690,0.198,0.000,0.802,0.5719
550,839,why would kim jong-un insult me by calling me ...,[kim],2017-11-12,260170,603848,0.080,0.125,0.795,-0.2960
551,840,will be going to north dakota today to discuss...,[tax],2017-09-06,16597,86174,0.000,0.081,0.919,-0.2960
552,841,will be having meetings and working the phones...,"[market, stock, market]",2017-11-22,14862,75474,0.000,0.000,1.000,0.0000
553,844,will be leaving for missouri soon for a speech...,[tax],2017-08-30,13359,79937,0.000,0.302,0.698,-0.7567
554,845,will be signing the biggest ever tax cut and r...,[tax],2017-12-22,18346,100377,0.000,0.087,0.913,-0.2732
555,846,"will soon be heading to davos, switzerland, to...",[economy],2018-01-25,27209,149035,0.157,0.000,0.843,0.6249
556,847,with 3.5 million americans receiving bonuses o...,[tax],2018-02-02,26480,105466,0.244,0.087,0.669,0.6124
557,848,"with irma and harvey devastation, tax cuts and...",[tax],2017-09-13,18970,90188,0.000,0.237,0.763,-0.6476
558,849,"with the great vote on cutting taxes, this cou...","[market, stock, market, tax]",2017-12-04,15819,87964,0.201,0.069,0.731,0.5983
559,853,working hard on the biggest tax cut in u.s. hi...,"[tax, jobs, jobs]",2017-10-25,18009,92443,0.288,0.102,0.610,0.8126
560,856,working on major trade deal with the united ki...,"[jobs, trade, jobs]",2017-07-25,15498,66880,0.221,0.071,0.709,0.6856
561,859,would very much appreciate saudi arabia doing ...,[stock],2017-11-04,17623,68403,0.293,0.000,0.707,0.7827
562,860,wouldn't it be great to repeal the very unfair...,[tax],2017-11-01,16610,79817,0.000,0.242,0.758,-0.7709
563,861,yesterday was a big day for the stock market. ...,"[market, stock, market, jobs, jobs]",2018-01-13,23389,114406,0.000,0.000,1.000,0.0000
564,866,"“$3 billion payoff: 101 utilities cut rates, c...",[tax],2018-06-07,10789,42199,0.177,0.143,0.680,0.1280
565,867,“american consumers are the most confident the...,"[market, market]",2018-02-27,13112,56865,0.472,0.000,0.528,0.9099
566,869,“bet founder: trump's economy is bringing blac...,"[economy, labor]",2018-04-06,29256,96143,0.000,0.000,1.000,0.0000
567,871,“disability applications plunge as economy str...,[economy],2018-06-23,13616,64253,0.000,0.268,0.732,-0.5106
568,872,“home prices reach new all-time highs in augus...,[price],2017-10-31,6155,28445,0.091,0.000,0.909,0.0258
569,873,“president trump is not getting the credit he ...,"[tax, economy]",2018-01-14,24074,109078,0.139,0.166,0.695,0.0813
570,875,“some 40 u.s. companies have responded to pres...,[tax],2018-01-04,16052,66519,0.000,0.095,0.905,-0.2732
571,876,“the unemployment rate remains at a 17-year lo...,[unemployment],2017-12-08,17071,63465,0.000,0.331,0.669,-0.7845
572,877,“trump rally: stocks put 2017 in the record bo...,[stock],2017-12-31,13348,63761,0.000,0.000,1.000,0.0000
573,878,“we ran out of words to describe how good the ...,"[jobs, jobs]",2018-06-02,16381,74620,0.146,0.000,0.854,0.4404

In [43]:
merged_table = merged_table.sort_values(["Date","Negative"])

#Dropped duplicate Dates
merged_table=merged_table.drop_duplicates(['Date'], keep='first', inplace=False)
merged_table.to_csv("Resource_CSVs/Twitter_RawData_Revised_method1.csv", index=False, header=True,encoding='utf-8-sig')
print (merged_table.head())
print (merged_table.describe())

     index                                              Tweet     Keyword_x  \
453    698  the massive tax cuts/reform that i have submit...         [tax]
471    724  the u.s. senate should switch to 51 votes, imm...         [tax]
372    549  rt @vp: our president is choosing to put ameri...  [jobs, jobs]
535    818  we need to be smart, vigilant and tough. we ne...         [ban]
449    693  the justice dept. should ask for an expedited ...         [ban]

           Date  Retweets   Likes  Positive  Negative  Neutral  Compound
453  2017-05-29     14921   71976     0.201     0.000    0.799    0.6468
471  2017-05-30     18760   74035     0.173     0.219    0.608   -0.1260
372  2017-06-02      9139       0     0.104     0.000    0.896    0.2732
535  2017-06-03     50195  169550     0.205     0.139    0.656    0.3382
449  2017-06-05     14070   62892     0.276     0.110    0.614    0.6588
            index       Retweets          Likes    Positive    Negative  \
count  267.000000     267.000000     267.000000  267.000000  267.000000
mean   398.198502   21010.172285   83373.906367    0.151105    0.047993
std    250.400510   20327.054975   59314.882522    0.127951    0.075666
min      0.000000    4843.000000       0.000000    0.000000    0.000000
25%    184.000000   13280.000000   58632.500000    0.000000    0.000000
50%    369.000000   17475.000000   80684.000000    0.134000    0.000000
75%    629.500000   23520.000000  102613.000000    0.244000    0.089000
max    872.000000  260170.000000  603848.000000    0.722000    0.359000

          Neutral    Compound
count  267.000000  267.000000
mean     0.800925    0.293379
std      0.140871    0.427488
min      0.278000   -0.838800
25%      0.697500    0.000000
50%      0.798000    0.361200
75%      0.896000    0.659250
max      1.000000    0.930500

In [41]:
# # Grouped by date 
# grouped_date = merged_table.groupby(['Date']).agg({"Likes": "sum","Retweets": "sum","Compound":"mean",
#                                                       "Negative":"mean","Neutral":"mean","Positive":"mean"}).apply(list).reset_index()
# grouped_date

grouped_date = merged_table[["Date", "Tweet","Keyword_x","Retweets", "Likes", 
                            "Positive", "Negative", "Neutral", "Compound"]]

print (grouped_date.head(20))
print (grouped_date.describe())

          Date                                              Tweet  \
0   2017-05-29  the massive tax cuts/reform that i have submit...
1   2017-05-30  the u.s. senate should switch to 51 votes, imm...
2   2017-06-02  rt @vp: our president is choosing to put ameri...
3   2017-06-03  we need to be smart, vigilant and tough. we ne...
4   2017-06-05  the justice dept. should ask for an expedited ...
5   2017-06-06  big meeting today with republican leadership c...
6   2017-06-09  it is time to rebuild our country, to bring ba...
7   2017-06-10  america is going to build again. under budget ...
8   2017-06-11  the democrats have no message,  not on economi...
9   2017-06-12  great numbers on the economy. all of our work,...
10  2017-06-13  heading to the great state of wisconsin to tal...
11  2017-06-15  crooked h destroyed phones w/ hammer, 'bleache...
12  2017-06-16  despite the phony witch hunt going on in ameri...
13  2017-06-17  back from miami where my cuban/american friend...
14  2017-06-18  the make america great again agenda is doing v...
15  2017-06-19  ralph norman, who is running for congress in s...
16  2017-06-20  while i greatly appreciate the efforts of pres...
17  2017-06-21  democrats would do much better as a party if t...
18  2017-06-22  mexico was just ranked the second deadliest co...
19  2017-06-23  .@flotus &amp; i were honored to host our firs...

              Keyword_x  Retweets   Likes  Positive  Negative  Neutral  \
0                 [tax]     14921   71976     0.201     0.000    0.799
1                 [tax]     18760   74035     0.173     0.219    0.608
2          [jobs, jobs]      9139       0     0.104     0.000    0.896
3                 [ban]     50195  169550     0.205     0.139    0.656
4                 [ban]     14070   62892     0.276     0.110    0.614
5                 [tax]     12214   68617     0.000     0.178    0.822
6   [jobs, jobs, build]     20592   87610     0.344     0.000    0.656
7               [build]     18653   76140     0.000     0.000    1.000
8     [tax, jobs, jobs]     28807  105391     0.119     0.087    0.794
9             [economy]     18011   84576     0.138     0.157    0.705
10         [jobs, jobs]     12340   64858     0.255     0.000    0.745
11                [ban]     51012  145571     0.057     0.130    0.813
12         [jobs, jobs]     23341  106898     0.309     0.000    0.691
13                [ban]     19847   99755     0.400     0.000    0.600
14         [jobs, jobs]     20065   96760     0.288     0.083    0.630
15                [tax]     12295   50574     0.244     0.058    0.698
16              [china]     17136   78376     0.206     0.000    0.794
17                [tax]     26669  111240     0.257     0.000    0.743
18       [trade, build]     41262  134825     0.000     0.000    1.000
19                [ban]      9629   51847     0.333     0.000    0.667

    Compound
0     0.6468
1    -0.1260
2     0.2732
3     0.3382
4     0.6588
5    -0.4389
6     0.8588
7     0.0000
8     0.2008
9    -0.1511
10    0.8016
11   -0.4215
12    0.8556
13    0.8847
14    0.7333
15    0.7003
16    0.7171
17    0.7088
18    0.0000
19    0.8176
            Retweets          Likes    Positive    Negative     Neutral  \
count     267.000000     267.000000  267.000000  267.000000  267.000000
mean    21010.172285   83373.906367    0.151105    0.047993    0.800925
std     20327.054975   59314.882522    0.127951    0.075666    0.140871
min      4843.000000       0.000000    0.000000    0.000000    0.278000
25%     13280.000000   58632.500000    0.000000    0.000000    0.697500
50%     17475.000000   80684.000000    0.134000    0.000000    0.798000
75%     23520.000000  102613.000000    0.244000    0.089000    0.896000
max    260170.000000  603848.000000    0.722000    0.359000    1.000000

         Compound
count  267.000000
mean     0.293379
std      0.427488
min     -0.838800
25%      0.000000
50%      0.361200
75%      0.659250
max      0.930500

In [26]:
#keeping only extremes of sentiments
# was playing around with the index we will need to figure this out

extreme_dates1 = grouped_date[(grouped_date['Compound'] >= .5) | (grouped_date['Compound'] <= -.5)]
# extreme_dates.drop(columns=[1])
print(extreme_dates1.head())
# extremes1 = (grouped_date['Compound'] >= 0.5) ~ (grouped_date['Compound'] <= 0.5)
#print(len(extreme_dates1))

          Date                                              Tweet  \
0   2017-05-29  the massive tax cuts/reform that i have submit...
4   2017-06-05  the justice dept. should ask for an expedited ...
6   2017-06-09  it is time to rebuild our country, to bring ba...
10  2017-06-13  heading to the great state of wisconsin to tal...
12  2017-06-16  despite the phony witch hunt going on in ameri...

              Keyword_x  Retweets   Likes  Positive  Negative  Neutral  \
0                 [tax]     14921   71976     0.201      0.00    0.799
4                 [ban]     14070   62892     0.276      0.11    0.614
6   [jobs, jobs, build]     20592   87610     0.344      0.00    0.656
10         [jobs, jobs]     12340   64858     0.255      0.00    0.745
12         [jobs, jobs]     23341  106898     0.309      0.00    0.691

    Compound
0     0.6468
4     0.6588
6     0.8588
10    0.8016
12    0.8556

In [27]:
base_url = 'https://www.alphavantage.co/query?function='

symbol1 = '^GSPC' 
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol1+'&outputsize=full&apikey='+ av_key
daily_response_SP500 = requests.get(time_series_url)
response_json_SP500 = daily_response_SP500.json()   

opening_SP500 = []
closing_SP500 = []
date_SP500 = []

for key in response_json_SP500["Time Series (Daily)"]:
    
    opening_SP500.append(response_json_SP500["Time Series (Daily)"][key]["1. open"])
    closing_SP500.append(response_json_SP500["Time Series (Daily)"][key]["4. close"])
    date_SP500.append(key)

SP500_df = pd.DataFrame({
    'Date': date_SP500,
    'S&P500 Open': opening_SP500,
    'S&P500 Close': closing_SP500
})


SP500_df = SP500_df[["Date", "S&P500 Open","S&P500 Close"]]
SP500_df = SP500_df.sort_values('Date', ascending = True)  

print (SP500_df.head())

# ^DJI is Dow Jones 30
symbol2 = '^DJI'
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol2+'&outputsize=full&apikey='+ av_key
daily_response_DJ = requests.get(time_series_url)
response_json_DJ = daily_response_DJ.json()   

opening_DJ = []
closing_DJ = []
date_DJ = []

for key in response_json_DJ["Time Series (Daily)"]:
    
    opening_DJ.append(response_json_DJ["Time Series (Daily)"][key]["1. open"])
    closing_DJ.append(response_json_DJ["Time Series (Daily)"][key]["4. close"])
    date_DJ.append(key)

DJ_df = pd.DataFrame({
    'Date': date_DJ,
    'DJ Open': opening_DJ,
    'DJ Close': closing_DJ
})


DJ_df = DJ_df[["Date", "DJ Open","DJ Close"]]
DJ_df = DJ_df.sort_values('Date', ascending = True)  

print (DJ_df.head())


# ^IXIC is NASDAQ
symbol3 = '^IXIC'
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol3+'&outputsize=full&apikey='+ av_key
daily_response_NAS = requests.get(time_series_url)
response_json_NAS = daily_response_NAS.json()   

opening_NAS = []
closing_NAS = []
date_NAS = []

for key in response_json_NAS["Time Series (Daily)"]:
    
    opening_NAS.append(response_json_NAS["Time Series (Daily)"][key]["1. open"])
    closing_NAS.append(response_json_NAS["Time Series (Daily)"][key]["4. close"])
    date_NAS.append(key)

NASDAQ_df = pd.DataFrame({
    'Date': date_NAS,
    'NAS Open': opening_NAS,
    'NAS Close': closing_NAS
})


NASDAQ_df = NASDAQ_df[["Date", "NAS Open","NAS Close"]]
NASDAQ_df = NASDAQ_df.sort_values('Date', ascending = True)  

print (NASDAQ_df.head())

            Date S&P500 Open S&P500 Close
4653  2000-01-03   1469.2500    1455.2200
4652  2000-01-04   1455.2200    1399.4200
4651  2000-01-05   1399.4200    1402.1100
4650  2000-01-06   1402.1100    1403.4500
4649  2000-01-07   1403.4500    1441.4700
            Date     DJ Open    DJ Close
4653  2000-01-03  11501.8496  11357.5098
4652  2000-01-04  11349.7500  10997.9297
4651  2000-01-05  10989.3701  11122.6504
4650  2000-01-06  11113.3701  11253.2598
4649  2000-01-07  11247.0596  11522.5596
            Date   NAS Open  NAS Close
4653  2000-01-03  4186.1899  4131.1499
4652  2000-01-04  4020.0000  3901.6899
4651  2000-01-05  3854.3501  3877.5400
4650  2000-01-06  3834.4399  3727.1299
4649  2000-01-07  3711.0901  3882.6201

In [28]:
# Calculating Sector performance for different sector indices
# 1. Banking
bank_data = os.path.join('raw_data', 'Banking.csv')
bank_df=pd.read_csv(bank_data)
bank_df =  bank_df[["Date", "Open", "Close"]]
bank_df = bank_df.rename(index=str, columns={"Open" : "Bank_Open","Close" : "Bank_Close"})
print (bank_df.head())

# 2. Biotech
biotech_data = os.path.join('raw_data', 'Biotech.csv')
biotech_df=pd.read_csv(biotech_data)
biotech_df =  biotech_df[["Date", "Open", "Close"]]
biotech_df = biotech_df.rename(index=str, columns={"Open" : "Biotech_Open","Close" : "Biotech_Close"})
print(biotech_df.head())


# 3. Healthcare
healthcare_data = os.path.join('raw_data', 'Healthcare.csv')
health_df=pd.read_csv(healthcare_data)
health_df =  health_df[["Date", "Open", "Close"]]
health_df = health_df.rename(index=str, columns={"Open" : "Healthcare_Open","Close" : "Healthcare_Close"})
print(health_df.head())

# 4. Housing
housing_data = os.path.join('raw_data', 'Housing.csv')
housing_df=pd.read_csv(housing_data)
housing_df =  housing_df[["Date", "Open", "Close"]]
housing_df = housing_df.rename(index=str, columns={"Open" : "Housing_Open","Close" : "Housing_Close"})
print(housing_df.head())

# 5. Industrials
industrial_data = os.path.join('raw_data', 'Industrials.csv')
industrial_df=pd.read_csv(industrial_data)
industrial_df =  industrial_df[["Date", "Open", "Close"]]
industrial_df = industrial_df.rename(index=str, columns={"Open" : "Industrial_Open","Close" : "Industrial_Close"})
print(industrial_df.head())

# 6. Insurance
insurance_data = os.path.join('raw_data', 'Insurance.csv')
insurance_df=pd.read_csv(insurance_data)
insurance_df =  insurance_df[["Date", "Open", "Close"]]
insurance_df = insurance_df.rename(index=str, columns={"Open" : "Insurance_Open","Close" : "Insurance_Close"})
print(insurance_df.head())

# 7. Oil & Gas
oil_data = os.path.join('raw_data', 'Oil&Gas.csv')
oil_df=pd.read_csv(oil_data)
oil_df =  oil_df[["Date", "Open", "Close"]]
oil_df = oil_df.rename(index=str, columns={"Open" : "Oil-Gas_Open","Close" : "Oil-Gas_Close"})
print(oil_df.head())

# 8. Semiconductor
semi_data = os.path.join('raw_data', 'Semiconductor.csv')
semi_df=pd.read_csv(semi_data)
semi_df =  semi_df[["Date", "Open", "Close"]]
semi_df = semi_df.rename(index=str, columns={"Open" : "Semiconductor_Open","Close" : "Semiconductor_Close"})
print(semi_df.head())

# 9. Telecom
telecom_data = os.path.join('raw_data', 'Telecom.csv')
telecom_df=pd.read_csv(telecom_data)
telecom_df =  telecom_df[["Date", "Open", "Close"]]
telecom_df = telecom_df.rename(index=str, columns={"Open" : "Telecom_Open","Close" : "Telecom_Close"})
print(telecom_df.head())


#10. Utility
utility_data = os.path.join('raw_data', 'Utility.csv')
utility_df=pd.read_csv(utility_data)
utility_df =  utility_df[["Date", "Open", "Close"]]
utility_df = utility_df.rename(index=str, columns={"Open" : "Utility_Open","Close" : "Utility_Close"})
print(utility_df.head())

         Date    Bank_Open   Bank_Close
0  2013-07-01  2221.090088  2249.080078
1  2013-07-02  2248.560059  2265.409912
2  2013-07-03  2256.489990  2272.570068
3  2013-07-05  2294.760010  2327.399902
4  2013-07-08  2335.919922  2328.719971
         Date  Biotech_Open  Biotech_Close
0  2013-07-01   1860.430054    1863.699951
1  2013-07-02   1862.780029    1865.569946
2  2013-07-03   1854.880005    1866.469971
3  2013-07-05   1882.619995    1900.589966
4  2013-07-08   1909.739990    1893.660034
         Date  Healthcare_Open  Healthcare_Close
0  2013-07-01       441.269989        440.750000
1  2013-07-02       440.420013        440.970001
2  2013-07-03       438.299988        440.700012
3  2013-07-05       444.700012        448.170013
4  2013-07-08       450.279999        447.660004
         Date  Housing_Open  Housing_Close
0  2013-07-01    179.690002     179.070007
1  2013-07-02    178.970001     177.070007
2  2013-07-03    176.580002     178.240005
3  2013-07-05    179.000000     174.199997
4  2013-07-08    176.039993     172.770004
         Date  Industrial_Open  Industrial_Close
0  2013-07-01      3085.030029       3100.330078
1  2013-07-02      3096.830078       3096.939941
2  2013-07-03      3082.330078       3104.429932
3  2013-07-05      3133.540039       3138.370117
4  2013-07-08      3154.320068       3161.520020
         Date  Insurance_Open  Insurance_Close
0  2013-07-01     5741.180176      5820.490234
1  2013-07-02     5815.439941      5790.430176
2  2013-07-03     5769.629883      5793.290039
3  2013-07-05     5856.350098      5882.740234
4  2013-07-08     5902.399902      5926.910156
         Date  Oil-Gas_Open  Oil-Gas_Close
0  2013-07-01    253.520004     255.880005
1  2013-07-02    255.690002     256.989990
2  2013-07-03    256.570007     256.329987
3  2013-07-05    257.260010     260.970001
4  2013-07-08    262.029999     263.350006
         Date  Semiconductor_Open  Semiconductor_Close
0  2013-07-01          470.019989           467.730011
1  2013-07-02          466.880005           468.179993
2  2013-07-03          465.750000           469.799988
3  2013-07-05          472.279999           476.119995
4  2013-07-08          477.470001           466.500000
         Date  Telecom_Open  Telecom_Close
0  2013-07-01    230.220001     229.970001
1  2013-07-02    229.330002     229.220001
2  2013-07-03    228.550003     230.889999
3  2013-07-05    231.660004     231.649994
4  2013-07-08    232.610001     231.919998
         Date  Utility_Open  Utility_Close
0  2013-07-01    493.859985     485.890015
1  2013-07-02    485.299988     485.839996
2  2013-07-03    484.299988     485.359985
3  2013-07-05    485.880005     482.869995
4  2013-07-08    484.369995     489.160004

In [29]:
# Merge Index Data Frames
data_frames = [SP500_df, DJ_df, NASDAQ_df, 
               bank_df, biotech_df, health_df,housing_df, industrial_df, 
               insurance_df, oil_df, semi_df, telecom_df, utility_df]

# To keep the values that belong to the same date you need to merge it on the DATE

df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['Date'],
                                            how='outer'), data_frames)

main_df=df_merged.dropna(axis=0)
main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close,Bank_Open,Bank_Close,Biotech_Open,...,Insurance_Open,Insurance_Close,Oil-Gas_Open,Oil-Gas_Close,Semiconductor_Open,Semiconductor_Close,Telecom_Open,Telecom_Close,Utility_Open,Utility_Close
3393,2013-07-01,1609.7800,1614.9600,14911.5996,14974.9600,3430.4800,3434.4900,2221.090088,2249.080078,1860.430054,...,5741.180176,5820.490234,253.520004,255.880005,470.019989,467.730011,230.220001,229.970001,493.859985,485.890015
3394,2013-07-02,1614.2900,1614.0800,14974.9600,14932.4102,3430.6899,3433.3999,2248.560059,2265.409912,1862.780029,...,5815.439941,5790.430176,255.690002,256.989990,466.880005,468.179993,229.330002,229.220001,485.299988,485.839996
3395,2013-07-03,1611.4800,1615.4100,14923.7305,14988.3701,3420.2700,3443.6699,2256.489990,2272.570068,1854.880005,...,5769.629883,5793.290039,256.570007,256.329987,465.750000,469.799988,228.550003,230.889999,484.299988,485.359985
3396,2013-07-05,1618.6500,1631.8900,14995.4600,15135.8398,3468.4800,3479.3799,2294.760010,2327.399902,1882.619995,...,5856.350098,5882.740234,257.260010,260.970001,472.279999,476.119995,231.660004,231.649994,485.880005,482.869995
3397,2013-07-08,1634.2000,1640.4600,15137.2197,15224.6904,3493.8101,3484.8301,2335.919922,2328.719971,1909.739990,...,5902.399902,5926.910156,262.029999,263.350006,477.470001,466.500000,232.610001,231.919998,484.369995,489.160004

In [30]:
# Clean this up
# Merge Index Data Frames
# fin_table1 = pd.merge(SP500_df, DJ_df, on= "Date", how = "left")
# main_df = pd.merge(fin_table1, NASDAQ_df, on= "Date", how = "left")
# main_df.head()

In [31]:
# Write to CSV -- to insure code runs if there is no internet connectivity and API can't be called
outfile = os.path.join("Resource_CSVs","Index_Sector_Raw_data.csv")
main_df.to_csv(outfile, encoding = "utf-8", index=False, header = True)

main_df=pd.read_csv('Resource_CSVs/Index_Sector_Raw_data.csv')
main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close,Bank_Open,Bank_Close,Biotech_Open,...,Insurance_Open,Insurance_Close,Oil-Gas_Open,Oil-Gas_Close,Semiconductor_Open,Semiconductor_Close,Telecom_Open,Telecom_Close,Utility_Open,Utility_Close
0,2013-07-01,1609.78,1614.96,14911.5996,14974.9600,3430.4800,3434.4900,2221.090088,2249.080078,1860.430054,...,5741.180176,5820.490234,253.520004,255.880005,470.019989,467.730011,230.220001,229.970001,493.859985,485.890015
1,2013-07-02,1614.29,1614.08,14974.9600,14932.4102,3430.6899,3433.3999,2248.560059,2265.409912,1862.780029,...,5815.439941,5790.430176,255.690002,256.989990,466.880005,468.179993,229.330002,229.220001,485.299988,485.839996
2,2013-07-03,1611.48,1615.41,14923.7305,14988.3701,3420.2700,3443.6699,2256.489990,2272.570068,1854.880005,...,5769.629883,5793.290039,256.570007,256.329987,465.750000,469.799988,228.550003,230.889999,484.299988,485.359985
3,2013-07-05,1618.65,1631.89,14995.4600,15135.8398,3468.4800,3479.3799,2294.760010,2327.399902,1882.619995,...,5856.350098,5882.740234,257.260010,260.970001,472.279999,476.119995,231.660004,231.649994,485.880005,482.869995
4,2013-07-08,1634.20,1640.46,15137.2197,15224.6904,3493.8101,3484.8301,2335.919922,2328.719971,1909.739990,...,5902.399902,5926.910156,262.029999,263.350006,477.470001,466.500000,232.610001,231.919998,484.369995,489.160004

In [32]:
# Calculate Returns On Indices
# Calculate Returns for S&P500

SP500_same_day =[]
SP500_one_day = []
SP500_two_day =[]

for row in range(len(main_df)):
   same_day_open= float(main_df["S&P500 Open"][row])
   same_day_close= float(main_df["S&P500 Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   SP500_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["S&P500 Close"][row])
       next_day_close = float(main_df["S&P500 Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       SP500_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       SP500_one_day.append(one_day_change)

   if row + 2 < len(main_df):
       prev_day_close= float(main_df["S&P500 Close"][row])
       
       two_day_close = float(main_df["S&P500 Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       SP500_two_day.append(two_day_change)
       
   else:
       two_day_change = 0
       SP500_two_day.append(two_day_change)


# Calculate Returns for Dow Jones

DJ_same_day =[]
DJ_one_day = []
DJ_two_day =[]

for row in range(len(main_df)):
   same_day_open= float(main_df["DJ Open"][row])
   same_day_close= float(main_df["DJ Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   DJ_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["DJ Close"][row])
       next_day_close = float(main_df["DJ Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       DJ_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       DJ_one_day.append(one_day_change)

   if row + 2 < len(main_df):
       prev_day_close= float(main_df["DJ Close"][row])
       
       two_day_close = float(main_df["DJ Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       DJ_two_day.append(two_day_change)
       
   else:
       two_day_change = 0
       DJ_two_day.append(two_day_change)
   

# Calculate Returns for Nasdaq

NASDAQ_same_day =[]
NASDAQ_one_day = []
NASDAQ_two_day =[]

for row in range(len(main_df)):
   same_day_open= float(main_df["NAS Open"][row])
   same_day_close= float(main_df["NAS Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   NASDAQ_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["NAS Close"][row])
       next_day_close = float(main_df["NAS Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       NASDAQ_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       NASDAQ_one_day.append(one_day_change)

   if row + 2 < len(main_df):
       prev_day_close= float(main_df["NAS Close"][row])
       
       two_day_close = float(main_df["NAS Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       NASDAQ_two_day.append(two_day_change)
       
   else:
       two_day_change = 0
       NASDAQ_two_day.append(two_day_change)

In [33]:
# Writting sector performance data to main data frame

main_df["S&P500 Same-Day Change"] = SP500_same_day
main_df["S&P500 1-Day Change"] = SP500_one_day
main_df["S&P500 2-Day Change"] = SP500_two_day

main_df["DJ Same-Day Change"] = DJ_same_day
main_df["DJ 1-Day Change"] = DJ_one_day
main_df["DJ 2-Day Change"] = DJ_two_day


main_df["NAS Same-Day Change"] = NASDAQ_same_day
main_df["NAS 1-Day Change"] = NASDAQ_one_day
main_df["NAS 2-Day Change"] = NASDAQ_two_day

main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close,Bank_Open,Bank_Close,Biotech_Open,...,Utility_Close,S&P500 Same-Day Change,S&P500 1-Day Change,S&P500 2-Day Change,DJ Same-Day Change,DJ 1-Day Change,DJ 2-Day Change,NAS Same-Day Change,NAS 1-Day Change,NAS 2-Day Change
0,2013-07-01,1609.78,1614.96,14911.5996,14974.9600,3430.4800,3434.4900,2221.090088,2249.080078,1860.430054,...,485.890015,0.32,-0.05,0.03,0.42,-0.28,0.09,0.12,-0.03,0.27
1,2013-07-02,1614.29,1614.08,14974.9600,14932.4102,3430.6899,3433.3999,2248.560059,2265.409912,1862.780029,...,485.839996,-0.01,0.08,1.10,-0.28,0.37,1.36,0.08,0.30,1.34
2,2013-07-03,1611.48,1615.41,14923.7305,14988.3701,3420.2700,3443.6699,2256.489990,2272.570068,1854.880005,...,485.359985,0.24,1.02,1.55,0.43,0.98,1.58,0.68,1.04,1.20
3,2013-07-05,1618.65,1631.89,14995.4600,15135.8398,3468.4800,3479.3799,2294.760010,2327.399902,1882.619995,...,482.869995,0.82,0.53,1.25,0.94,0.59,1.09,0.31,0.16,0.72
4,2013-07-08,1634.20,1640.46,15137.2197,15224.6904,3493.8101,3484.8301,2335.919922,2328.719971,1909.739990,...,489.160004,0.38,0.72,0.74,0.58,0.50,0.44,-0.26,0.56,1.03

In [34]:
# Calculate Returns On Sector
# 1. Calculate Returns for Banking Sector

Bank_same_day =[]
Bank_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Bank_Open"][row])
   same_day_close= float(main_df["Bank_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Bank_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Bank_Close"][row])
       next_day_close = float(main_df["Bank_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Bank_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Bank_one_day.append(one_day_change)


# 2. Calculate Returns for Biotechnology Sector 

Biotech_same_day =[]
Biotech_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Biotech_Open"][row])
   same_day_close= float(main_df["Biotech_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Biotech_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Biotech_Close"][row])
       next_day_close = float(main_df["Biotech_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Biotech_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Biotech_one_day.append(one_day_change)


# 3. Calculate Returns for Healthcare Sector

Healthcare_same_day =[]
Healthcare_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Healthcare_Open"][row])
   same_day_close= float(main_df["Healthcare_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Healthcare_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Healthcare_Close"][row])
       next_day_close = float(main_df["Healthcare_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Healthcare_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Healthcare_one_day.append(one_day_change)


# 4. Calculate Returns for Housing Sector

Housing_same_day =[]
Housing_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Housing_Open"][row])
   same_day_close= float(main_df["Housing_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Housing_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Housing_Close"][row])
       next_day_close = float(main_df["Housing_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Housing_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Housing_one_day.append(one_day_change)



# 5. Calculate Returns for Industrials Sector

Industrial_same_day =[]
Industrial_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Industrial_Open"][row])
   same_day_close= float(main_df["Industrial_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Industrial_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Industrial_Close"][row])
       next_day_close = float(main_df["Industrial_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Industrial_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Industrial_one_day.append(one_day_change)

# 6. Calculate Returns for Insurance Sector

Insurance_same_day =[]
Insurance_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Insurance_Open"][row])
   same_day_close= float(main_df["Insurance_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Insurance_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Insurance_Close"][row])
       next_day_close = float(main_df["Insurance_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Insurance_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Insurance_one_day.append(one_day_change)


# 7. Calculate Returns for Oil & Gas Sector

Oil_same_day =[]
Oil_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Oil-Gas_Open"][row])
   same_day_close= float(main_df["Oil-Gas_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Oil_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Oil-Gas_Close"][row])
       next_day_close = float(main_df["Oil-Gas_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Oil_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Oil_one_day.append(one_day_change)


# 8. Calculate Returns for Semiconductor Sector

Semiconductor_same_day =[]
Semiconductor_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Semiconductor_Open"][row])
   same_day_close= float(main_df["Semiconductor_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Semiconductor_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Semiconductor_Close"][row])
       next_day_close = float(main_df["Semiconductor_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Semiconductor_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Semiconductor_one_day.append(one_day_change)

# 9. Calculate Returns for Telecom Sector

Telecom_same_day =[]
Telecom_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Telecom_Open"][row])
   same_day_close= float(main_df["Telecom_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Telecom_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Telecom_Close"][row])
       next_day_close = float(main_df["Telecom_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Telecom_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Telecom_one_day.append(one_day_change)

#10. Calculate Returns for Utility Sector

Utility_same_day =[]
Utility_one_day = []

for row in range(len(main_df)):
   same_day_open= float(main_df["Utility_Open"][row])
   same_day_close= float(main_df["Utility_Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   Utility_same_day.append(same_day_change)
   
   if row + 1 < len(main_df):
       prev_day_close= float(main_df["Utility_Close"][row])
       next_day_close = float(main_df["Utility_Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       Utility_one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       Utility_one_day.append(one_day_change)

In [35]:
# Writting sector performance data to main data frame

# 1. Banking
main_df["Banking Same-Day Change"] = Bank_same_day
main_df["Banking 1-Day Change"] = Bank_one_day

# 2. Biotechnology Sector 
main_df["Biotech Same-Day Change"] = Biotech_same_day
main_df["Biotech 1-Day Change"] = Biotech_one_day

# 3. Healthcare Sector
main_df["Healthcare Same-Day Change"] = Healthcare_same_day
main_df["Healthcare 1-Day Change"] = Healthcare_one_day

# 4. Housing Sector
main_df["Housing Same-Day Change"] = Housing_same_day
main_df["Housing 1-Day Change"] = Housing_one_day

# 5. Industrials Sector
main_df["Industrial Same-Day Change"] = Industrial_same_day
main_df["Industrial 1-Day Change"] = Industrial_one_day

# 6. Insurance Sector
main_df["Insurance Same-Day Change"] = Insurance_same_day
main_df["Insurance 1-Day Change"] = Insurance_one_day

# 7. Oil & Gas Sector
main_df["Oil Same-Day Change"] = Oil_same_day
main_df["Oil 1-Day Change"] = Oil_one_day

# 8. Semiconductor Sector
main_df["Semiconductor Same-Day Change"] = Semiconductor_same_day
main_df["Semiconductor 1-Day Change"] = Semiconductor_one_day

# 9. Telecom Sector
main_df["Telecom Same-Day Change"] = Telecom_same_day
main_df["Telecom 1-Day Change"] = Telecom_one_day

#10. Utility Sector
main_df["Utility Same-Day Change"] = Utility_same_day
main_df["Utility 1-Day Change"] = Utility_one_day


# Write to CSV -- to insure code runs if there is no internet connectivity and API can't be called
outfile = os.path.join("Resource_CSVs","Index_Sector_Performance_data.csv")
main_df.to_csv(outfile, encoding = "utf-8", index=False, header = True)

main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close,Bank_Open,Bank_Close,Biotech_Open,...,Insurance Same-Day Change,Insurance 1-Day Change,Oil Same-Day Change,Oil 1-Day Change,Semiconductor Same-Day Change,Semiconductor 1-Day Change,Telecom Same-Day Change,Telecom 1-Day Change,Utility Same-Day Change,Utility 1-Day Change
0,2013-07-01,1609.78,1614.96,14911.5996,14974.9600,3430.4800,3434.4900,2221.090088,2249.080078,1860.430054,...,1.38,-0.52,0.93,0.43,-0.49,0.10,-0.11,-0.33,-1.61,-0.01
1,2013-07-02,1614.29,1614.08,14974.9600,14932.4102,3430.6899,3433.3999,2248.560059,2265.409912,1862.780029,...,-0.43,0.05,0.51,-0.26,0.28,0.35,-0.05,0.73,0.11,-0.10
2,2013-07-03,1611.48,1615.41,14923.7305,14988.3701,3420.2700,3443.6699,2256.489990,2272.570068,1854.880005,...,0.41,1.54,-0.09,1.81,0.87,1.35,1.02,0.33,0.22,-0.51
3,2013-07-05,1618.65,1631.89,14995.4600,15135.8398,3468.4800,3479.3799,2294.760010,2327.399902,1882.619995,...,0.45,0.75,1.44,0.91,0.81,-2.02,-0.00,0.12,-0.62,1.30
4,2013-07-08,1634.20,1640.46,15137.2197,15224.6904,3493.8101,3484.8301,2335.919922,2328.719971,1909.739990,...,0.42,0.72,0.50,1.03,-2.30,1.05,-0.30,1.12,0.99,0.63

In [36]:
# Merging Twitter data frame and Stock market data frame
merge_table = pd.merge(extreme_dates1, main_df, on= "Date", how = "left")
merge_table

,Date,Tweet,Keyword_x,Retweets,Likes,Positive,Negative,Neutral,Compound,S&P500 Open,...,Insurance Same-Day Change,Insurance 1-Day Change,Oil Same-Day Change,Oil 1-Day Change,Semiconductor Same-Day Change,Semiconductor 1-Day Change,Telecom Same-Day Change,Telecom 1-Day Change,Utility Same-Day Change,Utility 1-Day Change
0,2017-05-29,the massive tax cuts/reform that i have submit...,[tax],14921,71976,0.201,0.000,0.799,0.6468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-06-05,the justice dept. should ask for an expedited ...,[ban],14070,62892,0.276,0.110,0.614,0.6588,2437.8301,...,-0.72,-1.23,1.11,0.85,0.34,0.35,-0.45,-0.52,-0.35,-0.15
2,2017-06-09,"it is time to rebuild our country, to bring ba...","[jobs, jobs, build]",20592,87610,0.344,0.000,0.656,0.8588,2436.3899,...,0.57,0.38,3.49,0.55,-4.81,-0.51,-1.37,-0.01,0.24,-0.24
3,2017-06-13,heading to the great state of wisconsin to tal...,"[jobs, jobs]",12340,64858,0.255,0.000,0.745,0.8016,2434.1499,...,0.33,0.23,1.74,-3.89,-0.41,-1.06,0.54,-0.55,0.26,0.64
4,2017-06-16,despite the phony witch hunt going on in ameri...,"[jobs, jobs]",23341,106898,0.309,0.000,0.691,0.8556,2431.2400,...,0.56,-0.36,1.95,-0.64,-0.48,1.94,0.07,1.00,0.42,-0.40
5,2017-06-17,back from miami where my cuban/american friend...,[ban],19847,99755,0.400,0.000,0.600,0.8847,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2017-06-18,the make america great again agenda is doing v...,"[jobs, jobs]",20065,96760,0.288,0.083,0.630,0.7333,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2017-06-19,"ralph norman, who is running for congress in s...",[tax],12295,50574,0.244,0.058,0.698,0.7003,2442.5500,...,-0.49,-0.56,-0.68,-2.31,0.74,-1.20,0.58,-0.62,-0.45,0.09
8,2017-06-20,while i greatly appreciate the efforts of pres...,[china],17136,78376,0.206,0.000,0.794,0.7171,2450.6599,...,-0.46,-0.66,-0.53,-3.41,-1.33,1.17,-0.53,-0.28,0.04,-0.66
9,2017-06-21,democrats would do much better as a party if t...,[tax],26669,111240,0.257,0.000,0.743,0.7088,2439.3101,...,-0.76,-0.80,-3.44,-0.40,0.64,-0.23,-0.18,0.18,-0.62,-0.44
10,2017-06-23,.@flotus &amp; i were honored to host our firs...,[ban],9629,51847,0.333,0.000,0.667,0.8176,2434.6499,...,-0.05,0.18,0.35,0.25,0.34,-0.97,0.65,0.17,-0.30,0.77
11,2017-06-29,our new american energy policy will unlock mil...,"[jobs, jobs]",17678,73673,0.288,0.000,0.712,0.7964,2442.3799,...,-0.34,-0.64,0.55,0.24,-1.85,-0.53,-1.37,-0.09,-0.25,-0.11
12,2017-06-30,just finished a very good meeting with the pre...,[trade],18498,87535,0.148,0.000,0.852,0.5400,2429.2000,...,-0.79,1.09,-0.32,3.26,-0.96,-1.39,-0.66,-0.08,-0.29,-0.55
13,2017-07-02,"stock market at all time high, unemployment at...","[market, stock, market, unemployment, wages]",29868,128790,0.000,0.275,0.725,-0.7891,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,2017-07-03,at some point the fake news will be forced to ...,"[jobs, economy, jobs]",29369,124205,0.296,0.158,0.546,0.7424,2431.3899,...,0.67,-0.87,2.69,-3.12,-1.96,2.08,-0.21,-0.39,-0.83,-0.39
15,2017-07-04,rt @jacobawohl: @realdonaldtrump when obama wa...,"[market, stock, market]",17475,0,0.173,0.000,0.827,0.6360,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,2017-07-08,"leaving hamburg for washington, d.c. and the w...","[china, trade]",17111,93369,0.139,0.000,0.861,0.5719,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2017-07-09,the g 20 summit was a great success for the u....,[trade],15968,77211,0.234,0.101,0.665,0.6800,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,2017-07-12,"""after 14 years, u.s. beef hits chinese market...","[market, market, trade]",16729,66384,0.300,0.000,0.700,0.7184,2435.7500,...,0.16,0.21,-1.60,2.23,0.64,-0.25,-0.36,0.04,-0.12,-0.37
19,2017-07-14,great conversations with president @emmanuelma...,[trade],8663,48543,0.371,0.000,0.629,0.7579,2449.1599,...,0.38,0.40,1.06,0.16,0.89,-0.43,0.23,0.19,0.02,0.40
20,2017-07-15,"just got to the #uswomensopen in bedminster, n...","[market, stock, market]",10824,63149,0.163,0.000,0.837,0.6468,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,2017-07-17,"heading back to washington, d.c. much will be ...",[trade],14917,85370,0.272,0.000,0.728,0.6800,2459.5000,...,0.46,0.16,0.28,-0.36,-0.66,0.35,-0.01,-0.23,0.36,0.26
22,2017-07-22,the republican senators must step up to the pl...,[tax],18528,81871,0.157,0.000,0.843,0.6239,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,2017-07-31,"highest stock market ever, best economic numbe...","[market, stock, market, unemployment, wages]",28814,120685,0.192,0.341,0.467,-0.6239,2475.9399,...,-0.06,0.49,-0.25,-0.83,-1.07,0.55,-0.62,0.86,0.31,0.38
24,2017-08-02,i campaigned on creating a merit-based immigra...,[tax],19076,74595,0.273,0.000,0.727,0.5423,2480.3799,...,-0.30,0.29,0.97,-0.07,-1.41,-0.48,-0.18,0.11,0.81,0.46
25,2017-08-03,business is looking better than ever with busi...,"[market, stock, market]",15565,78869,0.233,0.000,0.767,0.7263,2476.0300,...,-0.45,0.62,-0.04,-0.01,-0.38,0.06,-0.15,0.21,0.69,-0.34
26,2017-08-04,excellent jobs numbers just released - and i h...,"[jobs, jobs]",18163,86177,0.166,0.000,0.834,0.6114,2476.8799,...,0.24,-0.68,-0.11,-2.66,-0.07,1.74,0.28,0.11,-0.03,0.22
27,2017-08-06,rt @ivankatrump: the administration is committ...,[kim],10266,0,0.407,0.000,0.593,0.8748,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,2017-08-07,just completed call with president moon of sou...,[sanctions],19247,96034,0.348,0.000,0.652,0.8795,2477.1399,...,-0.36,-0.95,-1.91,-1.88,1.42,-0.41,-0.04,-0.48,0.25,0.35
29,2017-08-09,my first order as president was to renovate an...,[nuclear],24111,102422,0.206,0.000,0.794,0.6901,2465.3501,...,0.08,-0.47,-1.50,-2.05,0.63,-2.79,-0.10,-2.04,-0.71,0.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,2018-02-24,unemployment claims are at the lowest level si...,[unemployment],15577,73355,0.000,0.269,0.731,-0.7184,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,2018-02-27,“american consumers are the most confident the...,"[market, market]",13112,56865,0.472,0.000,0.528,0.9099,2780.4500,...,-0.20,-1.51,-1.66,-3.57,-0.31,-0.92,-1.22,-0.49,-1.85,-0.55
89,2018-03-28,.@ustraderep just announced an agreement in pr...,[trade],11892,54386,0.309,0.000,0.691,0.8221,2611.3000,...,1.00,0.55,-1.98,2.52,-1.51,2.24,-1.62,2.15,-0.37,0.49
90,2018-04-06,"china, which is a great economic power, is con...","[china, trade]",23820,94954,0.204,0.000,0.796,0.6249,2645.8201,...,-1.00,-0.66,-1.37,-0.09,-1.55,0.68,-1.03,0.46,-0.73,0.10
91,2018-04-07,fire at trump tower is out. very confined (wel...,[build],23667,133839,0.272,0.095,0.633,0.6696,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,2018-04-10,very thankful for president xi of china’s kind...,"[china, tariff]",21985,105021,0.316,0.000,0.684,0.8122,2638.4099,...,0.29,-0.09,4.03,3.23,0.66,0.04,0.94,-0.02,-0.81,-0.18
93,2018-04-11,russia vows to shoot down any and all missiles...,[missile],64606,170567,0.091,0.218,0.691,-0.5423,2643.8899,...,0.45,0.64,3.17,0.98,0.67,1.87,0.37,1.43,0.02,-1.29
94,2018-04-13,"we are bringing back our factories, we are bri...","[jobs, jobs, factories]",24831,109861,0.157,0.000,0.843,0.5994,2676.8999,...,-0.76,1.27,0.62,-0.46,-1.89,0.23,-1.23,0.40,0.36,1.39
95,2018-04-17,"employment is up, taxes are down. enjoy!",[tax],24445,123198,0.368,0.000,0.632,0.5411,2692.7400,...,-0.57,0.11,-0.05,2.86,1.13,-1.03,1.18,0.13,0.97,-0.36
96,2018-04-19,rt @statedept: .@potus trump thanks prime mini...,[northkorea],8364,0,0.321,0.000,0.679,0.7269,2701.1599,...,0.66,-0.13,0.02,-0.65,-2.13,-1.17,0.10,-0.59,0.13,-0.93
97,2018-04-22,"kim strassel of the wsj just said, after revie...",[kim],24008,94034,0.000,0.125,0.875,-0.5106,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,2018-04-24,.@jimrenacci has worked so hard on tax reducti...,[tax],14635,59399,0.000,0.359,0.641,-0.8388,2680.8000,...,-0.66,-0.18,-0.84,1.45,-1.82,-0.12,-1.12,0.06,0.40,-0.01
99,2018-04-27,please do not forget the great help that my go...,[china],24538,111295,0.447,0.094,0.459,0.8826,2675.4700,...,-0.11,-1.29,-0.15,-0.47,-2.04,-1.09,-0.24,-1.49,1.19,-0.28
100,2018-04-28,look forward to being in the great state of mi...,"[jobs, jobs]",18514,96503,0.170,0.000,0.830,0.6249,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,2018-04-30,headline: “kim prepared to cede nuclear weapon...,"[kim, nuclear]",19515,91451,0.073,0.238,0.690,-0.6486,2682.5100,...,-1.40,0.09,-0.01,-1.30,-1.24,1.73,-1.32,-0.04,-0.47,-0.31
102,2018-05-03,our great financial team is in china trying to...,"[china, trade]",15672,77916,0.246,0.000,0.754,0.7345,2628.0801,...,-0.21,1.28,-0.77,1.40,1.48,2.31,0.44,1.56,-0.01,0.37
103,2018-05-21,china has agreed to buy massive amounts of add...,[china],17207,79992,0.270,0.000,0.730,0.7430,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,2018-05-24,it was my great honor to host a roundtable re:...,[ban],12886,57226,0.268,0.107,0.625,0.6597,2730.9399,...,-0.13,-0.34,-0.07,-4.28,0.37,0.88,-0.27,-0.42,0.79,0.47
105,2018-05-28,a democratic lawmaker just introduced a bill t...,[tax],26692,95713,0.212,0.082,0.706,0.5423,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,2018-06-04,in many ways this is the greatest economy in t...,[economy],17746,85203,0.303,0.000,0.697,0.8655,2741.6699,...,0.30,0.21,-1.12,0.66,0.69,0.41,0.06,0.29,-1.08,-0.69
107,2018-06-12,...got along great with kim jong-un who wants ...,[kim],18274,83302,0.291,0.000,0.709,0.8316,2785.6001,...,-0.78,-0.19,-1.03,-0.46,0.28,-0.13,0.57,0.22,1.29,-0.16
108,2018-06-13,...realize the economy is the best it’s ever b...,[economy],13638,74718,0.167,0.000,0.833,0.6369,2787.9399,...,-0.17,-0.50,-0.01,-0.08,-0.16,0.61,-0.19,1.30,-0.26,1.27
109,2018-06-15,u.s.a. jobs numbers are the best in 44 years. ...,"[jobs, jobs]",21601,99178,0.283,0.000,0.717,0.8360,2777.7800,...,0.76,0.17,-2.12,0.70,0.51,-0.99,0.32,-0.05,0.75,0.34
110,2018-06-17,our economy is perhaps better than it has ever...,[economy],15757,82944,0.209,0.000,0.791,0.6478,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,2018-06-20,rt @erictrump: it is hard to believe that the ...,[kim],16432,0,0.215,0.045,0.740,0.7430,2769.7300,...,-0.79,-1.05,0.00,-2.31,-0.14,-1.26,-0.27,-1.23,-0.07,0.33
112,2018-06-21,big supreme court win on internet sales tax - ...,[tax],14003,67245,0.396,0.000,0.604,0.9151,2769.2800,...,-1.09,0.62,-1.51,3.65,-1.94,-0.72,-1.03,0.17,0.39,0.73
113,2018-06-22,hope opec will increase output substantially. ...,[price],13238,63823,0.379,0.000,0.621,0.6696,2760.7900,...,0.15,-0.83,1.94,-2.94,-1.28,-3.13,-0.30,-1.84,0.52,1.62
114,2018-06-23,based on the tariffs and trade barriers long p...,"[tariff, trade]",19705,87393,0.157,0.000,0.843,0.6249,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,2018-06-25,rt @erictrump: record high economic optimism: ...,[economy],13999,0,0.363,0.000,0.637,0.8860,2742.9399,...,-0.53,-0.74,-2.64,1.53,-1.45,0.40,-1.06,0.55,1.34,0.01
116,2018-06-29,"rt @foxbusiness: .@ivankatrump: ""i think one o...",[economy],7448,0,0.255,0.000,0.745,0.7809,2727.1299,...,-0.51,0.00,-0.14,0.00,-0.62,0.00,-0.09,0.00,0.18,0.00

In [37]:
# for index, o1 in enumerate(pd.to_numeric(merge_table["S&P500 Open"])):
#     if math.isnan(o1):
#         date_NA = merge_table["Date"][index]
#         #print (date_NA)
#         date_NA = dt.strptime(date_NA, '%Y-%m-%d').date()
#         print (date_NA)

#         date_NA =date_NA  + timedelta(days=1)
#         print (date_NA)

#         date_NA_df = sp_df.loc[sp_df["Date"]== str(date_NA)]
        
#         s1 = float(date_NA_df["S&P500 Open"])
#         s2 = float(date_NA_df["S&P500 Close"])
#         s3 = float(date_NA_df["S&P500 Same-Day Change"])
#         s4 = float(date_NA_df["S&P500 1-Day Change"])
#         s5 = float(date_NA_df["S&P500 2-Day Change"])
#         merge_table["S&P500 Open"][index] = s1
#         merge_table["S&P500 Close"][index] = s2
#         merge_table["S&P500 Same-Day Change"][index] = s3
#         merge_table["S&P500 1-Day Change"][index] = s4
#         merge_table["S&P500 2-Day Change"][index] = s5

In [38]:
# count = merge_table['S&P500 Open'].value_counts()
# len(count)
merge_table1=merge_table.dropna(axis=0)
merge_table1.head(20)

,Date,Tweet,Keyword_x,Retweets,Likes,Positive,Negative,Neutral,Compound,S&P500 Open,...,Insurance Same-Day Change,Insurance 1-Day Change,Oil Same-Day Change,Oil 1-Day Change,Semiconductor Same-Day Change,Semiconductor 1-Day Change,Telecom Same-Day Change,Telecom 1-Day Change,Utility Same-Day Change,Utility 1-Day Change
1,2017-06-05,the justice dept. should ask for an expedited ...,[ban],14070,62892,0.276,0.110,0.614,0.6588,2437.8301,...,-0.72,-1.23,1.11,0.85,0.34,0.35,-0.45,-0.52,-0.35,-0.15
2,2017-06-09,"it is time to rebuild our country, to bring ba...","[jobs, jobs, build]",20592,87610,0.344,0.000,0.656,0.8588,2436.3899,...,0.57,0.38,3.49,0.55,-4.81,-0.51,-1.37,-0.01,0.24,-0.24
3,2017-06-13,heading to the great state of wisconsin to tal...,"[jobs, jobs]",12340,64858,0.255,0.000,0.745,0.8016,2434.1499,...,0.33,0.23,1.74,-3.89,-0.41,-1.06,0.54,-0.55,0.26,0.64
4,2017-06-16,despite the phony witch hunt going on in ameri...,"[jobs, jobs]",23341,106898,0.309,0.000,0.691,0.8556,2431.2400,...,0.56,-0.36,1.95,-0.64,-0.48,1.94,0.07,1.00,0.42,-0.40
7,2017-06-19,"ralph norman, who is running for congress in s...",[tax],12295,50574,0.244,0.058,0.698,0.7003,2442.5500,...,-0.49,-0.56,-0.68,-2.31,0.74,-1.20,0.58,-0.62,-0.45,0.09
8,2017-06-20,while i greatly appreciate the efforts of pres...,[china],17136,78376,0.206,0.000,0.794,0.7171,2450.6599,...,-0.46,-0.66,-0.53,-3.41,-1.33,1.17,-0.53,-0.28,0.04,-0.66
9,2017-06-21,democrats would do much better as a party if t...,[tax],26669,111240,0.257,0.000,0.743,0.7088,2439.3101,...,-0.76,-0.80,-3.44,-0.40,0.64,-0.23,-0.18,0.18,-0.62,-0.44
10,2017-06-23,.@flotus &amp; i were honored to host our firs...,[ban],9629,51847,0.333,0.000,0.667,0.8176,2434.6499,...,-0.05,0.18,0.35,0.25,0.34,-0.97,0.65,0.17,-0.30,0.77
11,2017-06-29,our new american energy policy will unlock mil...,"[jobs, jobs]",17678,73673,0.288,0.000,0.712,0.7964,2442.3799,...,-0.34,-0.64,0.55,0.24,-1.85,-0.53,-1.37,-0.09,-0.25,-0.11
12,2017-06-30,just finished a very good meeting with the pre...,[trade],18498,87535,0.148,0.000,0.852,0.5400,2429.2000,...,-0.79,1.09,-0.32,3.26,-0.96,-1.39,-0.66,-0.08,-0.29,-0.55
14,2017-07-03,at some point the fake news will be forced to ...,"[jobs, economy, jobs]",29369,124205,0.296,0.158,0.546,0.7424,2431.3899,...,0.67,-0.87,2.69,-3.12,-1.96,2.08,-0.21,-0.39,-0.83,-0.39
18,2017-07-12,"""after 14 years, u.s. beef hits chinese market...","[market, market, trade]",16729,66384,0.300,0.000,0.700,0.7184,2435.7500,...,0.16,0.21,-1.60,2.23,0.64,-0.25,-0.36,0.04,-0.12,-0.37
19,2017-07-14,great conversations with president @emmanuelma...,[trade],8663,48543,0.371,0.000,0.629,0.7579,2449.1599,...,0.38,0.40,1.06,0.16,0.89,-0.43,0.23,0.19,0.02,0.40
21,2017-07-17,"heading back to washington, d.c. much will be ...",[trade],14917,85370,0.272,0.000,0.728,0.6800,2459.5000,...,0.46,0.16,0.28,-0.36,-0.66,0.35,-0.01,-0.23,0.36,0.26
23,2017-07-31,"highest stock market ever, best economic numbe...","[market, stock, market, unemployment, wages]",28814,120685,0.192,0.341,0.467,-0.6239,2475.9399,...,-0.06,0.49,-0.25,-0.83,-1.07,0.55,-0.62,0.86,0.31,0.38
24,2017-08-02,i campaigned on creating a merit-based immigra...,[tax],19076,74595,0.273,0.000,0.727,0.5423,2480.3799,...,-0.30,0.29,0.97,-0.07,-1.41,-0.48,-0.18,0.11,0.81,0.46
25,2017-08-03,business is looking better than ever with busi...,"[market, stock, market]",15565,78869,0.233,0.000,0.767,0.7263,2476.0300,...,-0.45,0.62,-0.04,-0.01,-0.38,0.06,-0.15,0.21,0.69,-0.34
26,2017-08-04,excellent jobs numbers just released - and i h...,"[jobs, jobs]",18163,86177,0.166,0.000,0.834,0.6114,2476.8799,...,0.24,-0.68,-0.11,-2.66,-0.07,1.74,0.28,0.11,-0.03,0.22
28,2017-08-07,just completed call with president moon of sou...,[sanctions],19247,96034,0.348,0.000,0.652,0.8795,2477.1399,...,-0.36,-0.95,-1.91,-1.88,1.42,-0.41,-0.04,-0.48,0.25,0.35
29,2017-08-09,my first order as president was to renovate an...,[nuclear],24111,102422,0.206,0.000,0.794,0.6901,2465.3501,...,0.08,-0.47,-1.50,-2.05,0.63,-2.79,-0.10,-2.04,-0.71,0.31

In [39]:
# Write to CSV
outfile = os.path.join("Resource_CSVs","Main_data_revised.csv")
merge_table1.to_csv(outfile, encoding = "utf-8", index=False, header = True)