In [1]:
#Dependencies
import pandas as pd
import tweepy
from datetime import datetime as dt
from datetime import date
from datetime import timedelta
from pprint import pprint
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import re
from time import strftime
import math


from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

import matplotlib.dates as mdates
import matplotlib.cbook as cbook
from apikeys import consumer_key, consumer_secret, access_token, access_token_secret




import requests
import json
from apikeys import av_key
import pandas as pd
import os
import csv
import sys

In [2]:
# Setup Tweepy API Authentication
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())

In [3]:
# Target User
target_user = "@realDonaldTrump"


# Variable to hold Tweet Texts, created date, number of retweets, number of likes
tweet_texts = []
created_date =[]
retweets=[]
likes=[]


# Create a loop to iteratively run API requests to bypass weekly tweeter API limit
for x in range(1,160):

    # Get all tweets from Trump home feed (for specified number of pages)
    public_tweets = api.user_timeline(target_user, page=x)

    # Loop through all tweets
    for tweet in public_tweets:
        #Converting text to lower case
        txt = tweet['text'].lower()
        tweet_texts.append(txt)
        created_date.append(tweet["created_at"])
        retweets.append(tweet["retweet_count"])
        likes.append(tweet["favorite_count"])
        
#Created new dictionary to hold above variables
trump_tweets = {
                "Tweet" : tweet_texts,
                "Date" : created_date,
                "Retweets" : retweets,
                "Likes" : likes,
                }

#Converted dictionary to dataframe 
trump_tweets = pd.DataFrame(trump_tweets)
trump_tweets.head(5)

trump_tweets.to_csv("Twitter_RawData.csv", index=False, header=True,encoding='utf-8-sig')
# print(len(trump_tweets))

In [4]:
trump_tweets=pd.read_csv('Twitter_RawData.csv')
type(trump_tweets)
trump_tweets

,Date,Likes,Retweets,Tweet
0,Sat Jun 30 19:44:09 +0000 2018,37027,10394,"when people come into our country illegally, w..."
1,Sat Jun 30 19:31:42 +0000 2018,14620,3337,i will be interviewed by @mariabartiromo on su...
2,Sat Jun 30 19:26:12 +0000 2018,25999,6905,either we need to elect more republicans in no...
3,Sat Jun 30 19:17:42 +0000 2018,21723,5532,i never pushed the republicans in the house to...
4,Sat Jun 30 19:05:48 +0000 2018,27161,5918,a friend of mine and a man who has truly seen ...
5,Sat Jun 30 12:33:55 +0000 2018,71979,15015,i will be making my choice for justice of the ...
6,Sat Jun 30 11:37:03 +0000 2018,103793,30368,just spoke to king salman of saudi arabia and ...
7,Sat Jun 30 11:22:41 +0000 2018,101346,27009,"to the great and brave men and women of ice, d..."
8,Sat Jun 30 11:07:30 +0000 2018,77790,19814,the democrats are making a strong push to abol...
9,Sat Jun 30 10:59:46 +0000 2018,0,8054,rt @danscavino: “@govmikehuckabee: trump could...
10,Sat Jun 30 10:59:04 +0000 2018,0,17639,rt @realdonaldtrump: six months after our tax ...
11,Sat Jun 30 10:57:05 +0000 2018,0,11282,rt @realdonaldtrump: before going any further ...
12,Sat Jun 30 10:49:42 +0000 2018,0,5775,rt @ivankatrump: thank you @secpompeo. \nit wa...
13,Sat Jun 30 10:49:20 +0000 2018,0,3241,rt @ivankatrump: thank you senator alexander f...
14,Fri Jun 29 23:30:02 +0000 2018,68020,13999,the new plant being built by foxconn in wiscon...
15,Fri Jun 29 23:21:33 +0000 2018,0,6575,"rt @foxbusiness: .@ivankatrump: ""i think one o..."
16,Fri Jun 29 23:20:18 +0000 2018,0,10177,rt @scavino45: “@icegov new york operation lea...
17,Fri Jun 29 18:06:13 +0000 2018,75730,17639,"six months after our tax cuts, more than 6 mil..."
18,Fri Jun 29 17:59:22 +0000 2018,53079,11282,"before going any further today, i want to addr..."
19,Thu Jun 28 20:49:55 +0000 2018,96473,18157,"prior to departing wisconsin, i was briefed on..."
20,Thu Jun 28 19:09:42 +0000 2018,53682,12318,america is open for business! \nhttps://t.co/f...
21,Thu Jun 28 18:57:22 +0000 2018,93241,21483,"today, we broke ground on a plant that will pr..."
22,Thu Jun 28 13:06:01 +0000 2018,88325,16353,"i am in milwaukee, wisconsin, for meetings. so..."
23,Thu Jun 28 12:56:17 +0000 2018,71708,17035,....persecuted on old and/or totally unrelated...
24,Thu Jun 28 12:43:25 +0000 2018,78230,20482,when is bob mueller going to list his conflict...
25,Thu Jun 28 12:30:31 +0000 2018,79983,21254,peter strzok worked as the leader of the rigge...
26,Thu Jun 28 11:38:40 +0000 2018,61405,11892,just watched @sharkgregnorman on @foxandfriend...
27,Thu Jun 28 11:32:09 +0000 2018,49842,9287,"amy kremer, women for trump, was so great on @..."
28,Thu Jun 28 11:25:15 +0000 2018,91558,22848,russia continues to say they had nothing to do...
29,Thu Jun 28 11:02:01 +0000 2018,77830,18985,lover fbi agent peter strzok was given poor ma...
...,...,...,...,...
3145,Thu Jun 01 00:40:01 +0000 2017,109136,27600,crooked hillary clinton now blames everybody b...
3146,Wed May 31 21:52:54 +0000 2017,41661,7078,it was an honor to welcome the prime minister ...
3147,Wed May 31 20:04:45 +0000 2017,57578,12531,we traveled the world to strengthen long-stand...
3148,Wed May 31 13:08:41 +0000 2017,69355,13199,i will be announcing my decision on the paris ...
3149,Wed May 31 13:05:14 +0000 2017,62880,11709,"hopefully republican senators, good people all..."
3150,Wed May 31 11:14:48 +0000 2017,184839,50126,kathy griffin should be ashamed of herself. my...
3151,Wed May 31 10:45:27 +0000 2017,56489,12347,...case against him &amp; now wants to clear h...
3152,Wed May 31 10:37:42 +0000 2017,53454,13148,"so now it is reported that the democrats, who ..."
3153,Wed May 31 10:09:22 +0000 2017,199157,79690,"who can figure out the true meaning of ""covfef..."
3154,Tue May 30 14:01:16 +0000 2017,0,7170,rt @foxandfriends: jared kushner didn't sugges...
3155,Tue May 30 14:00:50 +0000 2017,0,5968,rt @scavino45: president trump pays respects a...
3156,Tue May 30 13:59:28 +0000 2017,74057,18767,"the u.s. senate should switch to 51 votes, imm..."
3157,Tue May 30 11:04:48 +0000 2017,82042,20522,russian officials must be laughing at the u.s....
3158,Tue May 30 10:40:36 +0000 2017,84978,21516,"we have a massive trade deficit with germany, ..."
3159,Mon May 29 12:36:37 +0000 2017,88182,14220,i look forward to paying my respects to our br...
3160,Mon May 29 12:35:34 +0000 2017,145174,34811,today we remember the men and women who made t...
3161,Mon May 29 12:18:52 +0000 2017,62399,11858,north korea has shown great disrespect for the...
3162,Mon May 29 12:11:59 +0000 2017,101695,25384,honoring the men and women who made the ultima...
3163,Mon May 29 00:20:11 +0000 2017,110107,27972,the fake news media works hard at disparaging ...
3164,Mon May 29 00:07:01 +0000 2017,71998,14923,the massive tax cuts/reform that i have submit...
3165,Sun May 28 23:57:19 +0000 2017,67173,12861,i suggest that we add more dollars to healthca...
3166,Sun May 28 14:43:53 +0000 2017,66546,15714,british prime minister may was very angry that...
3167,Sun May 28 12:45:45 +0000 2017,66954,13945,does anyone notice how the montana congression...
3168,Sun May 28 12:45:16 +0000 2017,56805,12444,....it is very possible that those sources don...
3169,Sun May 28 12:34:44 +0000 2017,74122,17955,whenever you see the words 'sources say' in th...
3170,Sun May 28 12:33:03 +0000 2017,68318,16513,it is my opinion that many of the leaks coming...
3171,Sun May 28 12:10:43 +0000 2017,78430,13448,just returned from europe. trip was a great su...
3172,Sun May 28 12:02:05 +0000 2017,60636,9075,big win in montana for republicans!
3173,Sat May 27 17:19:37 +0000 2017,87897,23115,bringing hundreds of billions of dollars back ...
3174,Sat May 27 16:22:01 +0000 2017,40706,7384,i look forward to reading the @commercegov 232...

In [37]:
# Created list of key words
# keywords = ['sad','earnings', 'election', 'futures', 'investor', 'low', 'market', 'nasdaq', 'north korea', 'stock',
# 'market', 'correction', 'trading', 'unemployment','wall street','china','ban',
# 'bull', 'kim', 'price', 'high', 'corporate', 'global warming', 'tariff', 'tax cut', 'jobs', 'economy', 'trade', 'missile', 'nuclear', 'jobs', 'wages',
# 'maga']

In [5]:
keywords=pd.read_csv('keywords.csv')
type(keywords)

pandas.core.frame.DataFrame

In [6]:
#Filtered tweets based on keywords and defined variables to hold
filtered_tweet_texts = []
filtered_created_date =[]
filtered_retweets=[]
filtered_likes=[]
filtered_id=[]
keys=[]
#Variables to hold sentiment analysis
compound_list = []
pos_list = []
neu_list = []
neg_list = []
# i = 0

# Looping through tweets
for tweet in trump_tweets.iterrows():
    for key in keywords['keywords']:
        #Used regular expression to find specific tweets based on keyword
        if re.search(key,tweet[1]['Tweet']):
            #Not all tweets will have keyword, catching tweets that match
            try:
                filtered_tweet_texts.append(tweet[1]["Tweet"])
                filtered_created_date.append(tweet[1]["Date"])
                filtered_retweets.append(tweet[1]["Retweets"])
                filtered_likes.append(tweet[1]["Likes"])
                keys.append(key)
                # Performed sentiment analysis using Vader
                compound = analyzer.polarity_scores(tweet[1]["Tweet"])["compound"]
                pos = analyzer.polarity_scores(tweet[1]["Tweet"])["pos"]
                neu = analyzer.polarity_scores(tweet[1]["Tweet"])["neu"]
                neg = analyzer.polarity_scores(tweet[1]["Tweet"])["neg"]
                compound_list.append(compound)
                pos_list.append(pos)
                neu_list.append(neu)
                neg_list.append(neg)
#                 i += 1   
            except:
                    print('Missing Data')                      
#Create new dictionary for filtered tweets

filtered_trump_tweets = {
                "Tweet" : filtered_tweet_texts,
                "Date" : filtered_created_date,
                "Retweets" : filtered_retweets,
                "Likes" : filtered_likes,
                "Keyword" : keys,
                "Positive" : pos_list,
                "Negative" : neg_list,
                "Neutral" : neu_list,
                "Compound" : compound_list,
                }               

#Convert dictionary to dataframe
filtered_trump_tweets = pd.DataFrame(filtered_trump_tweets)

#Convert date YYYY/MM/DD format
filtered_trump_tweets["Date"] = pd.to_datetime(filtered_trump_tweets["Date"])
filtered_trump_tweets["Date"] = filtered_trump_tweets["Date"].dt.strftime("%Y-%m-%d")

# filtered_trump_tweets

In [7]:
# Grouping by Tweets and concatenating keywords
grouped_keywords = filtered_trump_tweets.groupby(['Tweet'])['Keyword'].apply(list).reset_index()


#merged grouped data frame with filtered data frame
merged_table = pd.merge(grouped_keywords, filtered_trump_tweets, on="Tweet")
# merged_table=merged_table.drop_duplicates(['Tweet'], keep=False, inplace=False)

#Dropped unwanted column
merged_table = merged_table.drop(['Keyword_y'], axis=1)

#Dropped duplicate tweets
merged_table=merged_table.drop_duplicates(['Tweet'], keep='first', inplace=False).reset_index()

#Display
merged_table

,index,Tweet,Keyword_x,Compound,Date,Likes,Negative,Neutral,Positive,Retweets
0,0,"""after 14 years, u.s. beef hits chinese market...","[market, market, trade]",0.7184,2017-07-12,66406,0.000,0.700,0.300,16732
1,3,"""america's labor market continues to boom"" job...","[market, market, jobs, jobs, labor]",0.0000,2017-07-25,49003,0.000,1.000,0.000,11792
2,8,"""corporations have never made as much money as...","[jobs, jobs]",0.4199,2017-08-01,75982,0.000,0.883,0.117,16028
3,10,"""dow passes 23,000 for the first time, fueled ...",[earnings],0.5106,2017-10-17,44349,0.000,0.784,0.216,10859
4,11,"""iran hides behind its assertion of technical ...",[nuclear],-0.6124,2017-10-18,40718,0.227,0.773,0.000,11228
5,12,"""the real big story that affects everybody in ...",[tax],0.3818,2018-06-21,47194,0.081,0.775,0.143,11617
6,13,....and has been horrible on virginia economy....,[economy],-0.5848,2017-11-07,33620,0.296,0.704,0.000,6747
7,14,....and it will get even better with tax cuts!...,[tax],0.2481,2017-11-23,49772,0.164,0.597,0.238,9743
8,15,....and japan will put up with this much longe...,[china],-0.5294,2017-07-04,109585,0.120,0.880,0.000,28190
9,16,....because he doesn't even live there! he wan...,[tax],-0.7177,2017-06-19,41248,0.238,0.762,0.000,10102
10,17,....for the middle class. the house and senate...,[tax],0.2263,2017-11-01,54110,0.081,0.806,0.114,11091
11,18,....is making. working very hard on tax cuts f...,"[tax, jobs, jobs]",-0.4914,2017-11-07,41547,0.244,0.756,0.000,6694
12,21,....this now allows for the passage of large s...,[tax],-0.3595,2017-10-20,72732,0.098,0.902,0.000,14451
13,22,....we are finishing our study of tariffs on c...,[tariff],0.2500,2018-06-26,58582,0.000,0.917,0.083,12617
14,23,....we are getting other countries to reduce a...,"[tariff, trade]",0.0000,2018-06-26,65847,0.000,1.000,0.000,14581
15,25,....when i had harley-davidson officials over ...,[tariff],0.0000,2018-06-26,58021,0.000,1.000,0.000,12539
16,26,"...2nd amendment, strong military, isis, histo...","[market, stock, market, unemployment]",0.8439,2017-10-22,76175,0.171,0.405,0.424,16432
17,30,...and voted against the massive tax cut bill....,[tax],-0.7351,2018-05-16,44639,0.349,0.525,0.127,9524
18,31,...and west virginia. the fact is the fake new...,"[market, stock, market, jobs, jobs]",0.3612,2017-08-07,56937,0.121,0.661,0.218,11270
19,36,"...based on that, the military has hit isis ""m...",[price],-0.5848,2017-11-03,68161,0.172,0.828,0.000,14370
20,37,...but complain and obstruct. they made only b...,"[stock, trade]",-0.4753,2018-05-25,65600,0.221,0.667,0.112,14466
21,39,...congress must immediately pass border legis...,[nuclear],-0.2960,2018-04-02,88671,0.115,0.885,0.000,23096
22,40,...got along great with kim jong-un who wants ...,[kim],0.8316,2018-06-12,83338,0.000,0.709,0.291,18280
23,41,...haven’t even started yet! the u.s. has very...,[china],0.0000,2018-05-16,47662,0.000,1.000,0.000,9515
24,42,...if congress gives us the massive tax cuts (...,[tax],-0.2960,2017-10-11,52887,0.095,0.905,0.000,10613
25,43,"...lavar, you could have spent the next 5 to 1...",[china],-0.4215,2017-11-22,155122,0.118,0.882,0.000,36536
26,44,"...massive regulation cuts, 36 new legislative...",[tax],0.2481,2017-06-18,84523,0.189,0.645,0.165,17010
27,45,"...owed to wall street and the banks which, sa...",[ban],0.0258,2017-09-26,38910,0.101,0.758,0.141,7821
28,46,...people are now starting to recognize the am...,[build],0.8360,2017-10-01,77547,0.000,0.727,0.273,15105
29,47,...realize the economy is the best it’s ever b...,[economy],0.6369,2018-06-13,74754,0.000,0.833,0.167,13640
...,...,...,...,...,...,...,...,...,...,...
545,832,while i greatly appreciate the efforts of pres...,[china],0.7171,2017-06-20,78396,0.000,0.794,0.206,17123
546,833,why are democrats fighting massive tax cuts fo...,"[tax, jobs, jobs]",-0.7424,2017-11-16,97687,0.313,0.687,0.000,22462
547,836,"why is it that the wall street journal, though...",[tariff],0.2732,2018-06-02,80314,0.000,0.900,0.100,19108
548,837,why is the nfl getting massive tax breaks whil...,[tax],0.0000,2017-10-10,133401,0.000,1.000,0.000,30890
549,838,why isn’t the european union and canada inform...,"[tariff, trade]",0.0000,2018-06-08,98521,0.000,1.000,0.000,27073
550,840,"why should i, as president of the united state...",[trade],0.5719,2018-06-11,142750,0.000,0.802,0.198,33568
551,841,why would kim jong-un insult me by calling me ...,[kim],-0.2960,2017-11-12,603962,0.125,0.795,0.080,260242
552,842,will be going to north dakota today to discuss...,[tax],-0.2960,2017-09-06,86192,0.081,0.919,0.000,16609
553,843,will be having meetings and working the phones...,"[market, stock, market]",0.0000,2017-11-22,75508,0.000,1.000,0.000,14863
554,846,will be leaving for missouri soon for a speech...,[tax],-0.7567,2017-08-30,79961,0.302,0.698,0.000,13364
555,847,will be signing the biggest ever tax cut and r...,[tax],-0.2732,2017-12-22,100418,0.087,0.913,0.000,18352
556,848,"will soon be heading to davos, switzerland, to...",[economy],0.6249,2018-01-25,149098,0.000,0.843,0.157,27224
557,849,with 3.5 million americans receiving bonuses o...,[tax],0.6124,2018-02-02,105514,0.087,0.669,0.244,26492
558,850,"with irma and harvey devastation, tax cuts and...",[tax],-0.6476,2017-09-13,90212,0.237,0.763,0.000,18974
559,851,"with the great vote on cutting taxes, this cou...","[market, stock, market, tax]",0.5983,2017-12-04,88006,0.069,0.731,0.201,15821
560,855,working hard on the biggest tax cut in u.s. hi...,"[tax, jobs, jobs]",0.8126,2017-10-25,92474,0.102,0.610,0.288,18015
561,858,working on major trade deal with the united ki...,"[jobs, trade, jobs]",0.6856,2017-07-25,66905,0.071,0.709,0.221,15506
562,861,would very much appreciate saudi arabia doing ...,[stock],0.7827,2017-11-04,68422,0.000,0.707,0.293,17630
563,862,wouldn't it be great to repeal the very unfair...,[tax],-0.7709,2017-11-01,79836,0.242,0.758,0.000,16612
564,863,yesterday was a big day for the stock market. ...,"[market, stock, market, jobs, jobs]",0.0000,2018-01-13,114444,0.000,1.000,0.000,23404
565,868,"“$3 billion payoff: 101 utilities cut rates, c...",[tax],0.1280,2018-06-07,42212,0.143,0.680,0.177,10789
566,869,“american consumers are the most confident the...,"[market, market]",0.9099,2018-02-27,56889,0.000,0.528,0.472,13120
567,871,“bet founder: trump's economy is bringing blac...,"[economy, labor]",0.0000,2018-04-06,96164,0.000,1.000,0.000,29253
568,873,“disability applications plunge as economy str...,[economy],-0.5106,2018-06-23,64165,0.268,0.732,0.000,13617
569,874,“home prices reach new all-time highs in augus...,[price],0.0258,2017-10-31,28452,0.000,0.909,0.091,6157
570,875,“president trump is not getting the credit he ...,"[tax, economy]",0.0813,2018-01-14,109106,0.166,0.695,0.139,24085
571,877,“some 40 u.s. companies have responded to pres...,[tax],-0.2732,2018-01-04,66546,0.095,0.905,0.000,16063
572,878,“the unemployment rate remains at a 17-year lo...,[unemployment],-0.7845,2017-12-08,63493,0.331,0.669,0.000,17073
573,879,“trump rally: stocks put 2017 in the record bo...,[stock],0.0000,2017-12-31,63781,0.000,1.000,0.000,13352
574,880,“we ran out of words to describe how good the ...,"[jobs, jobs]",0.4404,2018-06-02,74654,0.000,0.854,0.146,16384

In [9]:
# Grouped by date 
grouped_date = merged_table.groupby(['Date']).agg({"Likes": "sum","Retweets": "sum","Compound":"mean",
                                                      "Negative":"mean","Neutral":"mean","Positive":"mean"}).apply(list).reset_index()
grouped_date

           Date   Likes  Retweets  Compound  Negative   Neutral  Positive
0    2017-05-27   87897     23115  0.000000  0.000000  1.000000  0.000000
1    2017-05-29  134397     26781  0.470500  0.084500  0.738000  0.177500
2    2017-05-30  159035     40283 -0.455050  0.237000  0.676500  0.086500
3    2017-06-02       0      9142  0.273200  0.000000  0.896000  0.104000
4    2017-06-03  169608     50216  0.338200  0.139000  0.656000  0.205000
5    2017-06-05  216063     49122  0.070000  0.138000  0.689667  0.172000
6    2017-06-06  184006     42020 -0.646000  0.276000  0.689500  0.034500
7    2017-06-09   87635     20599  0.858800  0.000000  0.656000  0.344000
8    2017-06-10  165918     39272  0.000000  0.000000  1.000000  0.000000
9    2017-06-11  284186     69759 -0.031267  0.111333  0.782667  0.106333
10   2017-06-12   84593     18018 -0.151100  0.157000  0.705000  0.138000
11   2017-06-13  191894     40284  0.040267  0.072667  0.819667  0.107667
12   2017-06-15  145610     51022 -0.421500  0.130000  0.813000  0.057000
13   2017-06-16  106922     23349  0.855600  0.000000  0.691000  0.309000
14   2017-06-17   99782     19851  0.884700  0.000000  0.600000  0.400000
15   2017-06-18  181315     37076  0.490700  0.136000  0.637500  0.226500
16   2017-06-19  172161     44025 -0.229300  0.189667  0.685333  0.125333
17   2017-06-20  300099     74750 -0.027900  0.157000  0.700750  0.142000
18   2017-06-21  111275     26683  0.708800  0.000000  0.743000  0.257000
19   2017-06-22  134854     41260  0.000000  0.000000  1.000000  0.000000
20   2017-06-23   51865      9635  0.817600  0.000000  0.667000  0.333000
21   2017-06-28   51354     12432 -0.400300  0.147000  0.779000  0.074000
22   2017-06-29  126334     29085  0.636550  0.000000  0.777500  0.222500
23   2017-06-30   87562     18510  0.540000  0.000000  0.852000  0.148000
24   2017-07-02  128834     29877 -0.789100  0.275000  0.725000  0.000000
25   2017-07-03  215234     48247  0.587550  0.160000  0.625000  0.215000
26   2017-07-04  404166    122723  0.046300  0.094750  0.795500  0.109750
27   2017-07-05  218853     48087 -0.275550  0.102000  0.853000  0.045000
28   2017-07-08   93405     17115  0.571900  0.000000  0.861000  0.139000
29   2017-07-09  155934     34505  0.227800  0.110000  0.731000  0.159000
..          ...     ...       ...       ...       ...       ...       ...
238  2018-05-21  373428     80351  0.375700  0.000000  0.888400  0.111600
239  2018-05-23  145479     30475  0.299700  0.048500  0.832000  0.119500
240  2018-05-24  119384     29639 -0.059300  0.250500  0.615500  0.134000
241  2018-05-25  183702     46384 -0.199050  0.163500  0.721500  0.115000
242  2018-05-27  119270     29271  0.421500  0.000000  0.882000  0.118000
243  2018-05-28  196369     51438  0.080250  0.156500  0.651500  0.192000
244  2018-05-29  121288     28929 -0.401900  0.193000  0.723000  0.084000
245  2018-05-30  159104     41904  0.051600  0.272000  0.500000  0.228000
246  2018-05-31   98089     31598  0.370700  0.000000  0.590000  0.410000
247  2018-06-02  446111    136150  0.284800  0.036571  0.811286  0.152143
248  2018-06-04  383578     84516 -0.094700  0.144200  0.759000  0.096800
249  2018-06-05   60071     14353 -0.359500  0.135000  0.783000  0.082000
250  2018-06-07  318300     75601  0.137940  0.080400  0.791600  0.128000
251  2018-06-08  469934    116428 -0.383480  0.140200  0.836800  0.023000
252  2018-06-09  313976     74372  0.121067  0.054333  0.862000  0.083333
253  2018-06-11  541704    125874  0.026275  0.096000  0.784000  0.120000
254  2018-06-12  331876     78065  0.407075  0.067500  0.676000  0.256500
255  2018-06-13  536695    113139 -0.073220  0.137600  0.758200  0.104200
256  2018-06-15   99219     21605  0.836000  0.000000  0.717000  0.283000
257  2018-06-17  162782     34461  0.782650  0.000000  0.696000  0.304000
258  2018-06-20       0     16436  0.743000  0.045000  0.740000  0.215000
259  2018-06-21  157674     35175  0.640600  0.027000  0.736333  0.236333
260  2018-06-22   63761     13239  0.669600  0.000000  0.621000  0.379000
261  2018-06-23  231943     48915  0.261600  0.089333  0.777000  0.133667
262  2018-06-24  114170     28288  0.421500  0.000000  0.872000  0.128000
263  2018-06-25   62608     28528  0.887250  0.060500  0.537500  0.402000
264  2018-06-26  355256     77846  0.218475  0.058750  0.794750  0.146500
265  2018-06-28  181566     37836 -0.263450  0.098000  0.902000  0.000000
266  2018-06-29   75730     24214  0.515450  0.077500  0.717500  0.205000
267  2018-06-30       0     17639  0.250000  0.143000  0.714000  0.143000

[268 rows x 7 columns]

In [10]:
#keeping only extremes of sentiments
# was playing around with the index we will need to figure this out

extreme_dates1 = grouped_date[(grouped_date['Compound'] >= .5) | (grouped_date['Compound'] <= -.5)].reset_index()
# extreme_dates.drop(columns=[1])
print(extreme_dates1.head())
# extremes1 = (grouped_date['Compound'] >= 0.5) ~ (grouped_date['Compound'] <= 0.5)
#print(len(extreme_dates1))

   index        Date   Likes  Retweets  Compound  Negative  Neutral  Positive
0      6  2017-06-06  184006     42020   -0.6460     0.276   0.6895    0.0345
1      7  2017-06-09   87635     20599    0.8588     0.000   0.6560    0.3440
2     13  2017-06-16  106922     23349    0.8556     0.000   0.6910    0.3090
3     14  2017-06-17   99782     19851    0.8847     0.000   0.6000    0.4000
4     18  2017-06-21  111275     26683    0.7088     0.000   0.7430    0.2570

In [14]:
base_url = 'https://www.alphavantage.co/query?function='

symbol1 = '^GSPC' 
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol1+'&outputsize=full&apikey='+ av_key
daily_response_SP500 = requests.get(time_series_url)
response_json_SP500 = daily_response_SP500.json()   

opening_SP500 = []
closing_SP500 = []
date_SP500 = []

for key in response_json_SP500["Time Series (Daily)"]:
    
    opening_SP500.append(response_json_SP500["Time Series (Daily)"][key]["1. open"])
    closing_SP500.append(response_json_SP500["Time Series (Daily)"][key]["4. close"])
    date_SP500.append(key)

SP500_df = pd.DataFrame({
    'Date': date_SP500,
    'S&P500 Open': opening_SP500,
    'S&P500 Close': closing_SP500
})


SP500_df = SP500_df[["Date", "S&P500 Open","S&P500 Close"]]
SP500_df = SP500_df.sort_values('Date', ascending = True)  

print (SP500_df.head())

# ^DJI is Dow Jones 30
symbol2 = '^DJI'
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol2+'&outputsize=full&apikey='+ av_key
daily_response_DJ = requests.get(time_series_url)
response_json_DJ = daily_response_DJ.json()   

opening_DJ = []
closing_DJ = []
date_DJ = []

for key in response_json_DJ["Time Series (Daily)"]:
    
    opening_DJ.append(response_json_DJ["Time Series (Daily)"][key]["1. open"])
    closing_DJ.append(response_json_DJ["Time Series (Daily)"][key]["4. close"])
    date_DJ.append(key)

DJ_df = pd.DataFrame({
    'Date': date_DJ,
    'DJ Open': opening_DJ,
    'DJ Close': closing_DJ
})


DJ_df = DJ_df[["Date", "DJ Open","DJ Close"]]
DJ_df = DJ_df.sort_values('Date', ascending = True)  

print (DJ_df.head())


# ^IXIC is NASDAQ
symbol3 = '^IXIC'
time_series_url = base_url +'TIME_SERIES_DAILY&symbol='+symbol3+'&outputsize=full&apikey='+ av_key
daily_response_NAS = requests.get(time_series_url)
response_json_NAS = daily_response_NAS.json()   

opening_NAS = []
closing_NAS = []
date_NAS = []

for key in response_json_NAS["Time Series (Daily)"]:
    
    opening_NAS.append(response_json_NAS["Time Series (Daily)"][key]["1. open"])
    closing_NAS.append(response_json_NAS["Time Series (Daily)"][key]["4. close"])
    date_NAS.append(key)

NASDAQ_df = pd.DataFrame({
    'Date': date_NAS,
    'NAS Open': opening_NAS,
    'NAS Close': closing_NAS
})


NASDAQ_df = NASDAQ_df[["Date", "NAS Open","NAS Close"]]
NASDAQ_df = NASDAQ_df.sort_values('Date', ascending = True)  

print (NASDAQ_df.head())



# Merge Data Frames

# Write to CSV
# outfile = os.path.join("fin.csv")
# sp_df.to_csv(outfile, encoding = "utf-8", index=False, header = True)

            Date S&P500 Open S&P500 Close
4652  2000-01-03   1469.2500    1455.2200
4651  2000-01-04   1455.2200    1399.4200
4650  2000-01-05   1399.4200    1402.1100
4649  2000-01-06   1402.1100    1403.4500
4648  2000-01-07   1403.4500    1441.4700
            Date     DJ Open    DJ Close
4652  2000-01-03  11501.8496  11357.5098
4651  2000-01-04  11349.7500  10997.9297
4650  2000-01-05  10989.3701  11122.6504
4649  2000-01-06  11113.3701  11253.2598
4648  2000-01-07  11247.0596  11522.5596
            Date   NAS Open  NAS Close
4652  2000-01-03  4186.1899  4131.1499
4651  2000-01-04  4020.0000  3901.6899
4650  2000-01-05  3854.3501  3877.5400
4649  2000-01-06  3834.4399  3727.1299
4648  2000-01-07  3711.0901  3882.6201

In [15]:
fin_table1 = pd.merge(SP500_df, DJ_df, on= "Date", how = "left")
main_df = pd.merge(fin_table1, NASDAQ_df, on= "Date", how = "left")
main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close
0,2000-01-03,1469.2500,1455.2200,11501.8496,11357.5098,4186.1899,4131.1499
1,2000-01-04,1455.2200,1399.4200,11349.7500,10997.9297,4020.0000,3901.6899
2,2000-01-05,1399.4200,1402.1100,10989.3701,11122.6504,3854.3501,3877.5400
3,2000-01-06,1402.1100,1403.4500,11113.3701,11253.2598,3834.4399,3727.1299
4,2000-01-07,1403.4500,1441.4700,11247.0596,11522.5596,3711.0901,3882.6201

In [17]:
# Calculate Returns for S&P500

SP500same_day =[]
SP500one_day = []
SP500two_day =[]

for row in range(len(SP500_df)):
   same_day_open= float(SP500_df["S&P500 Open"][row])
   same_day_close= float(SP500_df["S&P500 Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   SP500same_day.append(same_day_change)
   
   if row + 1 < len(SP500_df):
       prev_day_close= float(SP500_df["S&P500 Close"][row])
       next_day_close = float(SP500_df["S&P500 Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       SP500one_day.append(one_day_change)
       
   else:
       one_day_change = 0
       SP500one_day.append(one_day_change)

   if row + 2 < len(SP500_df):
       prev_day_close= float(SP500_df["S&P500 Close"][row])
       
       two_day_close = float(SP500_df["S&P500 Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       SP500two_day.append(two_day_change)
       
   else:
       two_day_change = 0
       SP500two_day.append(two_day_change)


# Calculate Returns for Dow Jones

DJsame_day =[]
DJone_day = []
DJtwo_day =[]

for row in range(len(DJ_df)):
   same_day_open= float(DJ_df["DJ Open"][row])
   same_day_close= float(DJ_df["DJ Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   DJsame_day.append(same_day_change)
   
   if row + 1 < len(DJ_df):
       prev_day_close= float(DJ_df["DJ Close"][row])
       next_day_close = float(DJ_df["DJ Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       DJone_day.append(one_day_change)
       
   else:
       one_day_change = 0
       DJone_day.append(one_day_change)

   if row + 2 < len(DJ_df):
       prev_day_close= float(DJ_df["DJ Close"][row])
       
       two_day_close = float(DJ_df["DJ Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       DJtwo_day.append(two_day_change)
       
   else:
       two_day_change = 0
       DJtwo_day.append(two_day_change)
   

# Calculate Returns for Nasdaq

NASDAQsame_day =[]
NASDAQone_day = []
NASDAQtwo_day =[]

for row in range(len(NASDAQ_df)):
   same_day_open= float(NASDAQ_df["NAS Open"][row])
   same_day_close= float(NASDAQ_df["NAS Close"][row])
   same_day_change = round(((same_day_close - same_day_open)/same_day_open ) * 100 ,2)
   NASDAQsame_day.append(same_day_change)
   
   if row + 1 < len(NASDAQ_df):
       prev_day_close= float(NASDAQ_df["NAS Close"][row])
       next_day_close = float(NASDAQ_df["NAS Close"][(row + 1)])
       one_day_change = round(((next_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       NASDAQone_day.append(one_day_change)
       
   else:
       one_day_change = 0
       NASDAQone_day.append(one_day_change)

   if row + 2 < len(NASDAQ_df):
       prev_day_close= float(NASDAQ_df["NAS Close"][row])
       
       two_day_close = float(NASDAQ_df["NAS Close"][(row + 2)])
       two_day_change = round(((two_day_close - prev_day_close)/prev_day_close ) * 100 ,2)
       NASDAQtwo_day.append(two_day_change)
       
   else:
       two_day_change = 0
       NASDAQtwo_day.append(two_day_change)

In [18]:
main_df["S&P500 Same-Day Change"] = SP500same_day
main_df["S&P500 1-Day Change"] = SP500one_day
main_df["S&P500 2-Day Change"] = SP500two_day

main_df["DJ Same-Day Change"] = DJsame_day
main_df["DJ 1-Day Change"] = DJone_day
main_df["DJ 2-Day Change"] = DJtwo_day


main_df["NAS Same-Day Change"] = NASDAQsame_day
main_df["NAS 1-Day Change"] = NASDAQone_day
main_df["NAS 2-Day Change"] = NASDAQtwo_day

main_df.head()

,Date,S&P500 Open,S&P500 Close,DJ Open,DJ Close,NAS Open,NAS Close,S&P500 Same-Day Change,S&P500 1-Day Change,S&P500 2-Day Change,DJ Same-Day Change,DJ 1-Day Change,DJ 2-Day Change,NAS Same-Day Change,NAS 1-Day Change,NAS 2-Day Change
0,2000-01-03,1469.2500,1455.2200,11501.8496,11357.5098,4186.1899,4131.1499,-0.32,-0.08,-0.69,-0.22,-0.23,-0.63,-0.45,-0.09,-0.87
1,2000-01-04,1455.2200,1399.4200,11349.7500,10997.9297,4020.0000,3901.6899,0.65,-0.61,0.25,0.63,-0.41,0.28,0.88,-0.78,0.77
2,2000-01-05,1399.4200,1402.1100,10989.3701,11122.6504,3854.3501,3877.5400,-1.06,0.87,0.65,-0.76,0.69,0.56,-1.86,1.57,1.17
3,2000-01-06,1402.1100,1403.4500,11113.3701,11253.2598,3834.4399,3727.1299,0.03,-0.22,1.17,0.01,-0.12,1.23,0.10,-0.39,1.73
4,2000-01-07,1403.4500,1441.4700,11247.0596,11522.5596,3711.0901,3882.6201,-0.94,1.39,1.20,-0.86,1.35,0.86,-1.30,2.14,2.40

In [19]:
merge_table = pd.merge(extreme_dates1, main_df, on= "Date", how = "left")
merge_table

,index,Date,Likes,Retweets,Compound,Negative,Neutral,Positive,S&P500 Open,S&P500 Close,...,NAS Close,S&P500 Same-Day Change,S&P500 1-Day Change,S&P500 2-Day Change,DJ Same-Day Change,DJ 1-Day Change,DJ 2-Day Change,NAS Same-Day Change,NAS 1-Day Change,NAS 2-Day Change
0,6,2017-06-06,184006,42020,-0.646000,0.27600,0.689500,0.034500,2431.9199,2429.3301,...,6275.0601,-0.19,0.19,0.69,-0.63,0.65,-0.12,2.81,-0.97,2.80
1,7,2017-06-09,87635,20599,0.858800,0.00000,0.656000,0.344000,2436.3899,2431.7700,...,6207.9199,1.30,-1.29,-1.31,0.70,-0.67,-0.58,2.94,-2.90,-2.46
2,13,2017-06-16,106922,23349,0.855600,0.00000,0.691000,0.309000,2431.2400,2433.1499,...,6151.7598,0.63,-0.61,0.01,1.21,-1.19,-0.40,-0.49,0.30,0.84
3,14,2017-06-17,99782,19851,0.884700,0.00000,0.600000,0.400000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,18,2017-06-21,111275,26683,0.708800,0.00000,0.743000,0.257000,2439.3101,2435.6101,...,6233.9502,0.96,-0.95,-1.33,0.34,-0.30,0.16,5.49,-3.28,-5.08
5,20,2017-06-23,51865,9635,0.817600,0.00000,0.667000,0.333000,2434.6499,2438.3000,...,6265.2500,-0.19,0.19,2.89,-0.35,0.38,2.74,0.30,0.49,7.13
6,22,2017-06-29,126334,29085,0.636550,0.00000,0.777500,0.222500,2442.3799,2419.7000,...,6144.3501,-2.80,2.88,3.97,-1.34,1.33,2.09,-7.37,7.80,11.60
7,23,2017-06-30,87562,18510,0.540000,0.00000,0.852000,0.148000,2429.2000,2423.4099,...,6140.4199,-1.04,1.06,0.65,-0.74,0.75,0.14,-3.22,3.53,2.79
8,24,2017-07-02,128834,29877,-0.789100,0.27500,0.725000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,25,2017-07-03,215234,48247,0.587550,0.16000,0.625000,0.215000,2431.3899,2429.0100,...,6110.0601,0.40,-0.40,-1.43,0.68,-0.60,-1.62,1.58,-0.72,-2.51
10,28,2017-07-08,93405,17115,0.571900,0.00000,0.861000,0.139000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,31,2017-07-12,366848,93389,0.655160,0.00000,0.728800,0.271200,2435.7500,2443.2500,...,6261.1699,-1.31,1.31,0.50,-0.55,0.58,-1.41,-4.03,4.49,5.64
12,32,2017-07-14,48561,8665,0.757900,0.00000,0.629000,0.371000,2449.1599,2459.2700,...,6312.4702,-2.15,2.19,3.65,-2.00,2.30,3.44,-1.32,2.84,6.39
13,33,2017-07-15,227544,43771,0.671967,0.00000,0.804000,0.196000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,34,2017-07-17,85386,14922,0.680000,0.00000,0.728000,0.272000,2459.5000,2459.1399,...,6314.4302,-1.40,1.42,2.26,-1.11,1.12,0.87,-3.26,3.45,7.45
15,37,2017-07-22,81899,18537,0.623900,0.00000,0.843000,0.157000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,42,2017-07-31,120712,28827,-0.623900,0.34100,0.467000,0.192000,2475.9399,2470.3000,...,6348.1201,-2.01,2.05,1.61,-1.85,2.06,0.89,-0.04,4.20,5.28
17,44,2017-08-02,74619,19083,0.542300,0.00000,0.727000,0.273000,2480.3799,2477.5701,...,6362.6499,-0.95,0.96,0.43,-0.29,0.37,-0.36,-4.83,5.32,6.19
18,48,2017-08-06,0,10271,0.874800,0.00000,0.593000,0.407000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,49,2017-08-07,325291,71416,0.539550,0.08125,0.665000,0.253750,2477.1399,2480.9099,...,6383.7700,-1.85,1.89,1.53,-0.81,0.92,0.61,-2.57,4.21,4.37
20,51,2017-08-09,102458,24118,0.690100,0.00000,0.794000,0.206000,2465.3501,2474.0200,...,6352.3301,-1.84,1.87,2.21,-1.52,1.60,1.85,-2.29,5.27,5.43
21,53,2017-08-11,217199,66637,0.603800,0.00000,0.767500,0.232500,2441.0400,2441.3201,...,6256.5601,-1.26,1.27,0.77,-0.46,0.48,0.23,-2.88,4.41,3.51
22,57,2017-08-18,83985,15173,0.648600,0.00000,0.798000,0.202000,2427.6399,2425.5500,...,6216.5298,-0.65,0.65,2.27,-0.62,0.67,1.09,0.80,0.98,6.73
23,58,2017-08-19,215014,51903,0.597050,0.08350,0.630500,0.285500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,60,2017-08-30,79961,13364,-0.756700,0.30200,0.698000,0.000000,2446.0601,2457.5901,...,6368.3101,1.38,-1.36,-2.45,2.34,-2.26,-4.21,-1.62,2.72,2.53
25,61,2017-08-31,0,9748,0.669600,0.00000,0.800000,0.200000,2462.6499,2471.6499,...,6428.6602,1.11,-1.10,-1.06,2.01,-1.99,-2.49,-1.27,-0.19,-1.49
26,64,2017-09-04,116017,25685,0.611400,0.00000,0.810000,0.190000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,69,2017-09-14,153530,34352,0.697300,0.00000,0.783000,0.217000,2494.5601,2495.6201,...,6429.0801,0.03,-0.03,-3.26,0.53,-0.46,-1.99,-0.76,0.81,-6.55
28,70,2017-09-15,208334,49099,-0.628800,0.23600,0.662000,0.102500,2495.6699,2500.2300,...,6448.4702,3.34,-3.23,-0.70,1.60,-1.55,2.17,8.58,-7.30,-4.47
29,71,2017-09-16,80203,15431,0.880500,0.00000,0.673000,0.327000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,128,2017-11-30,163161,32660,0.500150,0.04250,0.668500,0.289000,2633.9299,2647.5801,...,6873.9702,0.77,-0.76,1.31,0.07,-0.10,0.61,2.02,-2.76,2.00
46,133,2017-12-08,159035,38725,-0.572850,0.23700,0.722500,0.041000,2646.2100,2651.5000,...,6840.0801,-1.03,1.04,0.12,-1.01,1.03,-0.35,-1.43,2.20,-0.95
47,157,2018-01-07,97649,19439,0.585900,0.00000,0.798000,0.202000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,160,2018-01-10,87347,21925,0.598300,0.06600,0.743000,0.192000,2745.5500,2748.2300,...,7153.5698,0.22,-0.21,0.46,0.49,-0.60,0.57,2.49,-1.25,-1.83
49,166,2018-01-17,96622,23758,0.765000,0.00000,0.732000,0.268000,2784.9900,2802.5601,...,7298.2798,0.56,-0.55,-0.63,0.24,-0.25,-0.87,1.15,-1.26,0.14
50,168,2018-01-20,127467,27716,0.790600,0.00000,0.708000,0.292000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,170,2018-01-25,149098,27224,0.624900,0.00000,0.843000,0.157000,2846.2400,2839.2500,...,7411.1602,0.93,-0.92,-0.25,0.74,-0.71,0.02,1.93,-2.16,-0.46
52,171,2018-01-27,111373,21144,0.542300,0.09200,0.677000,0.231000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,173,2018-02-02,105514,26492,0.612400,0.08700,0.669000,0.244000,2808.9199,2762.1299,...,7240.9502,3.22,-3.12,-2.88,2.18,-2.16,-1.93,5.26,-7.35,-7.35
54,174,2018-02-04,132466,28914,0.624900,0.00000,0.823000,0.177000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,176,2018-02-07,110053,21180,0.700300,0.00000,0.784000,0.216000,2690.9500,2681.6599,...,7051.9800,1.83,-1.80,0.12,1.10,-1.07,0.07,3.66,-3.24,2.86
56,182,2018-02-23,115110,24212,0.537150,0.00000,0.789500,0.210500,2715.8000,2747.3000,...,7337.3901,-0.84,0.85,1.45,-0.67,0.63,0.39,-3.23,2.35,6.47
57,183,2018-02-24,153037,35412,-0.560050,0.31700,0.586000,0.097500,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,184,2018-02-27,106529,24996,0.844100,0.04050,0.552500,0.407000,2780.4500,2744.2800,...,7330.3501,1.64,-1.61,-1.22,1.62,-1.56,-0.92,3.32,-2.53,-2.87
59,202,2018-03-28,268223,61259,0.567600,0.00000,0.807333,0.192667,2611.3000,2605.0000,...,6949.2300,-0.49,0.49,1.25,-1.16,1.19,1.70,3.56,-0.49,1.31
60,211,2018-04-10,105066,21991,0.812200,0.00000,0.684000,0.316000,2638.4099,2656.8701,...,7094.2998,0.01,-0.01,-1.76,0.05,0.06,-2.21,-0.47,-0.45,-1.98
61,212,2018-04-11,170656,64649,-0.542300,0.21800,0.691000,0.091000,2643.8899,2642.1899,...,7069.0298,1.78,-1.75,-2.19,2.16,-2.28,-1.91,1.36,-1.54,-4.63
62,217,2018-04-19,0,8372,0.726900,0.00000,0.679000,0.321000,2701.1599,2693.1299,...,7238.0601,2.43,-2.37,-0.61,3.30,-3.16,-1.82,-3.69,2.71,7.08
63,220,2018-04-22,94073,24024,-0.510600,0.12500,0.875000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,221,2018-04-24,59426,14641,-0.838800,0.35900,0.641000,0.000000,2680.8000,2634.5601,...,7007.3501,-0.47,0.47,-2.03,-0.80,0.82,-0.73,-0.23,-0.03,-3.00
65,223,2018-04-28,96530,18529,0.624900,0.00000,0.830000,0.170000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,224,2018-04-30,91498,19527,-0.648600,0.23800,0.690000,0.073000,2682.5100,2648.0500,...,7066.2700,-1.27,1.29,-0.68,-1.82,1.93,-0.05,-0.62,0.20,-3.07
67,226,2018-05-03,77952,15678,0.734500,0.00000,0.754000,0.246000,2628.0801,2629.7300,...,7088.1499,0.93,-0.93,-2.26,0.10,-0.09,-0.98,1.08,-1.83,-4.31
68,256,2018-06-15,99219,21605,0.836000,0.00000,0.717000,0.283000,2777.7800,2779.6599,...,7746.3799,-0.68,0.69,-0.38,-1.35,1.40,0.19,1.75,-1.61,-4.20
69,257,2018-06-17,162782,34461,0.782650,0.00000,0.696000,0.304000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,258,2018-06-20,0,16436,0.743000,0.04500,0.740000,0.215000,2769.7300,2767.3201,...,7781.5098,-0.44,0.44,1.77,0.39,-0.35,0.18,-2.55,1.85,5.19
71,259,2018-06-21,157674,35175,0.640600,0.02700,0.736333,0.236333,2769.2800,2749.7600,...,7712.9502,-1.31,1.32,0.20,-0.50,0.53,0.10,-2.73,3.28,-0.98
72,260,2018-06-22,63761,13239,0.669600,0.00000,0.621000,0.379000,2760.7900,2754.8799,...,7692.8198,1.12,-1.11,-3.72,0.34,-0.43,-2.76,1.19,-4.13,-7.96
73,263,2018-06-25,62608,28528,0.887250,0.06050,0.537500,0.402000,2742.9399,2717.0701,...,7532.0098,2.71,-2.64,-2.73,2.45,-2.34,-3.47,4.62,-4.00,-0.13
74,266,2018-06-29,75730,24214,0.515450,0.07750,0.717500,0.205000,2727.1299,2718.3701,...,7510.2998,-0.95,0.00,0.00,-1.25,0.00,0.00,-1.31,0.00,0.00

In [ ]:
# for index, o1 in enumerate(pd.to_numeric(merge_table["S&P500 Open"])):
#     if math.isnan(o1):
#         date_NA = merge_table["Date"][index]
#         #print (date_NA)
#         date_NA = dt.strptime(date_NA, '%Y-%m-%d').date()
#         print (date_NA)

#         date_NA =date_NA  + timedelta(days=1)
#         print (date_NA)

#         date_NA_df = sp_df.loc[sp_df["Date"]== str(date_NA)]
        
#         s1 = float(date_NA_df["S&P500 Open"])
#         s2 = float(date_NA_df["S&P500 Close"])
#         s3 = float(date_NA_df["S&P500 Same-Day Change"])
#         s4 = float(date_NA_df["S&P500 1-Day Change"])
#         s5 = float(date_NA_df["S&P500 2-Day Change"])
#         merge_table["S&P500 Open"][index] = s1
#         merge_table["S&P500 Close"][index] = s2
#         merge_table["S&P500 Same-Day Change"][index] = s3
#         merge_table["S&P500 1-Day Change"][index] = s4
#         merge_table["S&P500 2-Day Change"][index] = s5

In [20]:
# count = merge_table['S&P500 Open'].value_counts()
# len(count)
merge_table1=merge_table.dropna(axis=0)
merge_table1.head(20)

,index,Date,Likes,Retweets,Compound,Negative,Neutral,Positive,S&P500 Open,S&P500 Close,...,NAS Close,S&P500 Same-Day Change,S&P500 1-Day Change,S&P500 2-Day Change,DJ Same-Day Change,DJ 1-Day Change,DJ 2-Day Change,NAS Same-Day Change,NAS 1-Day Change,NAS 2-Day Change
0,6,2017-06-06,184006,42020,-0.64600,0.27600,0.6895,0.03450,2431.9199,2429.3301,...,6275.0601,-0.19,0.19,0.69,-0.63,0.65,-0.12,2.81,-0.97,2.80
1,7,2017-06-09,87635,20599,0.85880,0.00000,0.6560,0.34400,2436.3899,2431.7700,...,6207.9199,1.30,-1.29,-1.31,0.70,-0.67,-0.58,2.94,-2.90,-2.46
2,13,2017-06-16,106922,23349,0.85560,0.00000,0.6910,0.30900,2431.2400,2433.1499,...,6151.7598,0.63,-0.61,0.01,1.21,-1.19,-0.40,-0.49,0.30,0.84
4,18,2017-06-21,111275,26683,0.70880,0.00000,0.7430,0.25700,2439.3101,2435.6101,...,6233.9502,0.96,-0.95,-1.33,0.34,-0.30,0.16,5.49,-3.28,-5.08
5,20,2017-06-23,51865,9635,0.81760,0.00000,0.6670,0.33300,2434.6499,2438.3000,...,6265.2500,-0.19,0.19,2.89,-0.35,0.38,2.74,0.30,0.49,7.13
6,22,2017-06-29,126334,29085,0.63655,0.00000,0.7775,0.22250,2442.3799,2419.7000,...,6144.3501,-2.80,2.88,3.97,-1.34,1.33,2.09,-7.37,7.80,11.60
7,23,2017-06-30,87562,18510,0.54000,0.00000,0.8520,0.14800,2429.2000,2423.4099,...,6140.4199,-1.04,1.06,0.65,-0.74,0.75,0.14,-3.22,3.53,2.79
9,25,2017-07-03,215234,48247,0.58755,0.16000,0.6250,0.21500,2431.3899,2429.0100,...,6110.0601,0.40,-0.40,-1.43,0.68,-0.60,-1.62,1.58,-0.72,-2.51
11,31,2017-07-12,366848,93389,0.65516,0.00000,0.7288,0.27120,2435.7500,2443.2500,...,6261.1699,-1.31,1.31,0.50,-0.55,0.58,-1.41,-4.03,4.49,5.64
12,32,2017-07-14,48561,8665,0.75790,0.00000,0.6290,0.37100,2449.1599,2459.2700,...,6312.4702,-2.15,2.19,3.65,-2.00,2.30,3.44,-1.32,2.84,6.39
14,34,2017-07-17,85386,14922,0.68000,0.00000,0.7280,0.27200,2459.5000,2459.1399,...,6314.4302,-1.40,1.42,2.26,-1.11,1.12,0.87,-3.26,3.45,7.45
16,42,2017-07-31,120712,28827,-0.62390,0.34100,0.4670,0.19200,2475.9399,2470.3000,...,6348.1201,-2.01,2.05,1.61,-1.85,2.06,0.89,-0.04,4.20,5.28
17,44,2017-08-02,74619,19083,0.54230,0.00000,0.7270,0.27300,2480.3799,2477.5701,...,6362.6499,-0.95,0.96,0.43,-0.29,0.37,-0.36,-4.83,5.32,6.19
19,49,2017-08-07,325291,71416,0.53955,0.08125,0.6650,0.25375,2477.1399,2480.9099,...,6383.7700,-1.85,1.89,1.53,-0.81,0.92,0.61,-2.57,4.21,4.37
20,51,2017-08-09,102458,24118,0.69010,0.00000,0.7940,0.20600,2465.3501,2474.0200,...,6352.3301,-1.84,1.87,2.21,-1.52,1.60,1.85,-2.29,5.27,5.43
21,53,2017-08-11,217199,66637,0.60380,0.00000,0.7675,0.23250,2441.0400,2441.3201,...,6256.5601,-1.26,1.27,0.77,-0.46,0.48,0.23,-2.88,4.41,3.51
22,57,2017-08-18,83985,15173,0.64860,0.00000,0.7980,0.20200,2427.6399,2425.5500,...,6216.5298,-0.65,0.65,2.27,-0.62,0.67,1.09,0.80,0.98,6.73
24,60,2017-08-30,79961,13364,-0.75670,0.30200,0.6980,0.00000,2446.0601,2457.5901,...,6368.3101,1.38,-1.36,-2.45,2.34,-2.26,-4.21,-1.62,2.72,2.53
25,61,2017-08-31,0,9748,0.66960,0.00000,0.8000,0.20000,2462.6499,2471.6499,...,6428.6602,1.11,-1.10,-1.06,2.01,-1.99,-2.49,-1.27,-0.19,-1.49
27,69,2017-09-14,153530,34352,0.69730,0.00000,0.7830,0.21700,2494.5601,2495.6201,...,6429.0801,0.03,-0.03,-3.26,0.53,-0.46,-1.99,-0.76,0.81,-6.55